#ifndef LFORTRAN_ASR_TO_ASR_DIALECT_H
#define LFORTRAN_ASR_TO_ASR_DIALECT_H

#include <libasr/asr.h>
#include <libasr/asr_utils.h>

#include <cstdint>
#include <string>
#include <vector>

#include <libasr/diagnostics.h>

extern "C" {
#include <asr_dialect_api.h>
}

namespace LCompilers {

class AsrDialectError {
public:
    diag::Diagnostic d;
    explicit AsrDialectError(const std::string &msg)
        : d{diag::Diagnostic(msg, diag::Level::Error, diag::Stage::CodeGen)} {}
    AsrDialectError(const std::string &msg, const Location &loc)
        : d{diag::Diagnostic(msg, diag::Level::Error, diag::Stage::CodeGen,
              {diag::Label("", {loc})})} {}
};
// Co-generated visitors by handwritten and ASDL-to-ASR-dialect.py
// Initial ones are handled by users, the rest are written by ASDL-to-ASR-dialect.py
class ASRToAsrDialectVisitor : public ASR::BaseVisitor<ASRToAsrDialectVisitor> {
public:
    typedef MLIR_OpHandle MLIR_ValueHandle;

    Arena *arena = nullptr;
    Allocator *asr_al = nullptr;
    MLIR_Context ctx{};
    MLIR_LocationHandle mlir_loc = MLIR_INVALID_HANDLE;
    MLIR_BlockHandle module_block = MLIR_INVALID_HANDLE;
    MLIR_OpHandle module_op = MLIR_INVALID_HANDLE;
    MLIR_ValueHandle last_value = MLIR_INVALID_HANDLE;
    bool block_terminated = false;
    bool suppress_module_append = false;
    Location current_stmt_loc{};

    MLIR_LocationHandle default_loc();
    MLIR_LocationHandle loc(const Location &l);

    static uint32_t asr_kind_to_bits(int64_t kind);
    MLIR_TypeHandle asr_dialect_type(const ASR::ttype_t &t);
    MLIR_TypeHandle convert_type(const ASR::ttype_t &t);

    MLIR_OpHandle *emit_expr_op_array(ASR::expr_t **exprs, size_t n);
    MLIR_OpHandle *emit_stmt_op_array(ASR::stmt_t **stmts, size_t n, size_t *n_out = nullptr);
    MLIR_OpHandle *copy_op_handles(const std::vector<MLIR_OpHandle> &ops, size_t *n_out);
    MLIR_OpHandle *emit_array_index_op_array(const ASR::array_index_t *indices, size_t n);
    MLIR_OpHandle *emit_product_op_array(const void *nodes, size_t n);

    string emit_symbol_ref(const ASR::symbol_t &s);
    string emit_identifier_seq(char **ids, size_t n);
    string emit_symbol_seq_ref(ASR::symbol_t **syms, size_t n);

    MLIR_ValueHandle emit_product_value(ASR::asr_t &node);
    MLIR_ValueHandle emit_product_seq_value(ASR::asr_t **nodes, size_t n);
    MLIR_TypeHandle emit_type_seq_value(ASR::ttype_t **types, size_t n);

    void emit_module_skeleton();
    void append_module(MLIR_OpHandle op);
    void append_current_stmt(MLIR_OpHandle op);

    enum class ScopeRegion { Module, Symtab, Metadata, Body };
    ScopeRegion scope_region = ScopeRegion::Module;
    std::vector<MLIR_OpHandle> scope_symtab;
    std::vector<MLIR_OpHandle> scope_metadata;
    std::vector<MLIR_OpHandle> scope_body;

    MLIR_RegionHandle emit_empty_region();
    MLIR_RegionHandle emit_op_vector_region(const std::vector<MLIR_OpHandle> &ops);
    MLIR_RegionHandle emit_stmt_region(ASR::stmt_t **stmts, size_t n);
    void append_scope_op(MLIR_OpHandle op);

    MLIR_ValueHandle emit_expr(ASR::expr_t &e);
    MLIR_ValueHandle emit_stmt(ASR::stmt_t &s);
    MLIR_ValueHandle emit_expr_seq_value(ASR::expr_t **exprs, size_t n);
    MLIR_ValueHandle emit_stmt_seq_value(ASR::stmt_t **stmts, size_t n);

    MLIR_ValueHandle emit_do_loop_head(const ASR::do_loop_head_t &h);
    MLIR_ValueHandle emit_array_index(const ASR::array_index_t &idx);
    MLIR_ValueHandle emit_print_op(ASR::expr_t &text_expr);
    void emit_print_exprs(ASR::expr_t &text_expr);

    void visit_Print(const ASR::Print_t &x);
    void visit_StringFormat(const ASR::StringFormat_t &x);
    void visit_FileWrite(const ASR::FileWrite_t &x);
    void visit_DoLoop(const ASR::DoLoop_t &x);
    void visit_If(const ASR::If_t &x);
    void visit_WhileLoop(const ASR::WhileLoop_t &x);
    void visit_Variable(const ASR::Variable_t &v);
    void visit_Var(const ASR::Var_t &x);
    void visit_ArrayConstructor(const ASR::ArrayConstructor_t &x);
    void visit_ArrayItem(const ASR::ArrayItem_t &x);
    void visit_ArrayConstant(const ASR::ArrayConstant_t &x);

    // >>> GENERATED VISITOR DECLARATIONS >>>
// Generated by asdl_to_asr_dialect.py — do not edit.

    void visit_ArrayBound(const ASR::ArrayBound_t &x);
    void visit_ArrayBroadcast(const ASR::ArrayBroadcast_t &x);
    void visit_ArrayIsContiguous(const ASR::ArrayIsContiguous_t &x);
    void visit_ArrayPack(const ASR::ArrayPack_t &x);
    void visit_ArrayPhysicalCast(const ASR::ArrayPhysicalCast_t &x);
    void visit_ArrayRank(const ASR::ArrayRank_t &x);
    void visit_ArrayReshape(const ASR::ArrayReshape_t &x);
    void visit_ArraySection(const ASR::ArraySection_t &x);
    void visit_ArraySize(const ASR::ArraySize_t &x);
    void visit_ArrayTranspose(const ASR::ArrayTranspose_t &x);
    void visit_BitCast(const ASR::BitCast_t &x);
    void visit_CLoc(const ASR::CLoc_t &x);
    void visit_CPtrCompare(const ASR::CPtrCompare_t &x);
    void visit_Cast(const ASR::Cast_t &x);
    void visit_CoarrayRef(const ASR::CoarrayRef_t &x);
    void visit_CompilerOptions(const ASR::CompilerOptions_t &x);
    void visit_ComplexBinOp(const ASR::ComplexBinOp_t &x);
    void visit_ComplexCompare(const ASR::ComplexCompare_t &x);
    void visit_ComplexConstant(const ASR::ComplexConstant_t &x);
    void visit_ComplexConstructor(const ASR::ComplexConstructor_t &x);
    void visit_ComplexIm(const ASR::ComplexIm_t &x);
    void visit_ComplexRe(const ASR::ComplexRe_t &x);
    void visit_ComplexUnaryMinus(const ASR::ComplexUnaryMinus_t &x);
    void visit_DictConstant(const ASR::DictConstant_t &x);
    void visit_DictContains(const ASR::DictContains_t &x);
    void visit_DictItem(const ASR::DictItem_t &x);
    void visit_DictLen(const ASR::DictLen_t &x);
    void visit_DictPop(const ASR::DictPop_t &x);
    void visit_EnumConstructor(const ASR::EnumConstructor_t &x);
    void visit_EnumName(const ASR::EnumName_t &x);
    void visit_EnumStaticMember(const ASR::EnumStaticMember_t &x);
    void visit_EnumValue(const ASR::EnumValue_t &x);
    void visit_FunctionCall(const ASR::FunctionCall_t &x);
    void visit_FunctionParam(const ASR::FunctionParam_t &x);
    void visit_GetPointer(const ASR::GetPointer_t &x);
    void visit_GpuBlockIndex(const ASR::GpuBlockIndex_t &x);
    void visit_GpuBlockSize(const ASR::GpuBlockSize_t &x);
    void visit_GpuThreadIndex(const ASR::GpuThreadIndex_t &x);
    void visit_Iachar(const ASR::Iachar_t &x);
    void visit_Ichar(const ASR::Ichar_t &x);
    void visit_IfExp(const ASR::IfExp_t &x);
    void visit_ImpliedDoLoop(const ASR::ImpliedDoLoop_t &x);
    void visit_IntegerBinOp(const ASR::IntegerBinOp_t &x);
    void visit_IntegerBitLen(const ASR::IntegerBitLen_t &x);
    void visit_IntegerBitNot(const ASR::IntegerBitNot_t &x);
    void visit_IntegerCompare(const ASR::IntegerCompare_t &x);
    void visit_IntegerConstant(const ASR::IntegerConstant_t &x);
    void visit_IntegerUnaryMinus(const ASR::IntegerUnaryMinus_t &x);
    void visit_IntrinsicArrayFunction(const ASR::IntrinsicArrayFunction_t &x);
    void visit_IntrinsicElementalFunction(const ASR::IntrinsicElementalFunction_t &x);
    void visit_IntrinsicImpureFunction(const ASR::IntrinsicImpureFunction_t &x);
    void visit_ListCompare(const ASR::ListCompare_t &x);
    void visit_ListConcat(const ASR::ListConcat_t &x);
    void visit_ListConstant(const ASR::ListConstant_t &x);
    void visit_ListContains(const ASR::ListContains_t &x);
    void visit_ListCount(const ASR::ListCount_t &x);
    void visit_ListItem(const ASR::ListItem_t &x);
    void visit_ListLen(const ASR::ListLen_t &x);
    void visit_ListRepeat(const ASR::ListRepeat_t &x);
    void visit_ListSection(const ASR::ListSection_t &x);
    void visit_LogicalBinOp(const ASR::LogicalBinOp_t &x);
    void visit_LogicalCompare(const ASR::LogicalCompare_t &x);
    void visit_LogicalConstant(const ASR::LogicalConstant_t &x);
    void visit_LogicalNot(const ASR::LogicalNot_t &x);
    void visit_NamedExpr(const ASR::NamedExpr_t &x);
    void visit_OverloadedBinOp(const ASR::OverloadedBinOp_t &x);
    void visit_OverloadedBoolOp(const ASR::OverloadedBoolOp_t &x);
    void visit_OverloadedCompare(const ASR::OverloadedCompare_t &x);
    void visit_OverloadedStringConcat(const ASR::OverloadedStringConcat_t &x);
    void visit_OverloadedUnaryMinus(const ASR::OverloadedUnaryMinus_t &x);
    void visit_PointerAssociated(const ASR::PointerAssociated_t &x);
    void visit_PointerNullConstant(const ASR::PointerNullConstant_t &x);
    void visit_PointerToCPtr(const ASR::PointerToCPtr_t &x);
    void visit_RealBinOp(const ASR::RealBinOp_t &x);
    void visit_RealCompare(const ASR::RealCompare_t &x);
    void visit_RealConstant(const ASR::RealConstant_t &x);
    void visit_RealCopySign(const ASR::RealCopySign_t &x);
    void visit_RealSqrt(const ASR::RealSqrt_t &x);
    void visit_RealUnaryMinus(const ASR::RealUnaryMinus_t &x);
    void visit_SetConstant(const ASR::SetConstant_t &x);
    void visit_SetContains(const ASR::SetContains_t &x);
    void visit_SetLen(const ASR::SetLen_t &x);
    void visit_SetPop(const ASR::SetPop_t &x);
    void visit_SizeOfType(const ASR::SizeOfType_t &x);
    void visit_StringChr(const ASR::StringChr_t &x);
    void visit_StringCompare(const ASR::StringCompare_t &x);
    void visit_StringConcat(const ASR::StringConcat_t &x);
    void visit_StringConstant(const ASR::StringConstant_t &x);
    void visit_StringContains(const ASR::StringContains_t &x);
    void visit_StringItem(const ASR::StringItem_t &x);
    void visit_StringLen(const ASR::StringLen_t &x);
    void visit_StringOrd(const ASR::StringOrd_t &x);
    void visit_StringPhysicalCast(const ASR::StringPhysicalCast_t &x);
    void visit_StringRepeat(const ASR::StringRepeat_t &x);
    void visit_StringSection(const ASR::StringSection_t &x);
    void visit_StructConstant(const ASR::StructConstant_t &x);
    void visit_StructConstructor(const ASR::StructConstructor_t &x);
    void visit_StructInstanceMember(const ASR::StructInstanceMember_t &x);
    void visit_StructStaticMember(const ASR::StructStaticMember_t &x);
    void visit_SymbolicCompare(const ASR::SymbolicCompare_t &x);
    void visit_TupleCompare(const ASR::TupleCompare_t &x);
    void visit_TupleConcat(const ASR::TupleConcat_t &x);
    void visit_TupleConstant(const ASR::TupleConstant_t &x);
    void visit_TupleContains(const ASR::TupleContains_t &x);
    void visit_TupleItem(const ASR::TupleItem_t &x);
    void visit_TupleLen(const ASR::TupleLen_t &x);
    void visit_TypeInquiry(const ASR::TypeInquiry_t &x);
    void visit_UnionConstructor(const ASR::UnionConstructor_t &x);
    void visit_UnionInstanceMember(const ASR::UnionInstanceMember_t &x);
    void visit_UnsignedIntegerBinOp(const ASR::UnsignedIntegerBinOp_t &x);
    void visit_UnsignedIntegerBitNot(const ASR::UnsignedIntegerBitNot_t &x);
    void visit_UnsignedIntegerCompare(const ASR::UnsignedIntegerCompare_t &x);
    void visit_UnsignedIntegerConstant(const ASR::UnsignedIntegerConstant_t &x);
    void visit_UnsignedIntegerUnaryMinus(const ASR::UnsignedIntegerUnaryMinus_t &x);
    void visit_Allocate(const ASR::Allocate_t &x);
    void visit_Assert(const ASR::Assert_t &x);
    void visit_Assign(const ASR::Assign_t &x);
    void visit_Assignment(const ASR::Assignment_t &x);
    void visit_Associate(const ASR::Associate_t &x);
    void visit_AssociateBlockCall(const ASR::AssociateBlockCall_t &x);
    void visit_BlockCall(const ASR::BlockCall_t &x);
    void visit_CPtrToPointer(const ASR::CPtrToPointer_t &x);
    void visit_Cycle(const ASR::Cycle_t &x);
    void visit_DebugCheckArrayBounds(const ASR::DebugCheckArrayBounds_t &x);
    void visit_DictClear(const ASR::DictClear_t &x);
    void visit_DictInsert(const ASR::DictInsert_t &x);
    void visit_DoConcurrentLoop(const ASR::DoConcurrentLoop_t &x);
    void visit_ErrorStop(const ASR::ErrorStop_t &x);
    void visit_Exit(const ASR::Exit_t &x);
    void visit_ExplicitDeallocate(const ASR::ExplicitDeallocate_t &x);
    void visit_Expr(const ASR::Expr_t &x);
    void visit_FileBackspace(const ASR::FileBackspace_t &x);
    void visit_FileClose(const ASR::FileClose_t &x);
    void visit_FileEndfile(const ASR::FileEndfile_t &x);
    void visit_FileInquire(const ASR::FileInquire_t &x);
    void visit_FileOpen(const ASR::FileOpen_t &x);
    void visit_FileRead(const ASR::FileRead_t &x);
    void visit_FileRewind(const ASR::FileRewind_t &x);
    void visit_Flush(const ASR::Flush_t &x);
    void visit_ForAllSingle(const ASR::ForAllSingle_t &x);
    void visit_ForEach(const ASR::ForEach_t &x);
    void visit_GoTo(const ASR::GoTo_t &x);
    void visit_GoToTarget(const ASR::GoToTarget_t &x);
    void visit_GpuKernelLaunch(const ASR::GpuKernelLaunch_t &x);
    void visit_GpuSync(const ASR::GpuSync_t &x);
    void visit_IfArithmetic(const ASR::IfArithmetic_t &x);
    void visit_ImplicitDeallocate(const ASR::ImplicitDeallocate_t &x);
    void visit_IntrinsicImpureSubroutine(const ASR::IntrinsicImpureSubroutine_t &x);
    void visit_ListAppend(const ASR::ListAppend_t &x);
    void visit_ListClear(const ASR::ListClear_t &x);
    void visit_ListInsert(const ASR::ListInsert_t &x);
    void visit_ListRemove(const ASR::ListRemove_t &x);
    void visit_Nullify(const ASR::Nullify_t &x);
    void visit_OMPRegion(const ASR::OMPRegion_t &x);
    void visit_ReAlloc(const ASR::ReAlloc_t &x);
    void visit_Return(const ASR::Return_t &x);
    void visit_Select(const ASR::Select_t &x);
    void visit_SelectRank(const ASR::SelectRank_t &x);
    void visit_SelectType(const ASR::SelectType_t &x);
    void visit_SetClear(const ASR::SetClear_t &x);
    void visit_SetInsert(const ASR::SetInsert_t &x);
    void visit_SetRemove(const ASR::SetRemove_t &x);
    void visit_Stop(const ASR::Stop_t &x);
    void visit_SubroutineCall(const ASR::SubroutineCall_t &x);
    void visit_SyncAll(const ASR::SyncAll_t &x);
    void visit_SyncMemory(const ASR::SyncMemory_t &x);
    void visit_Where(const ASR::Where_t &x);
// <<< END GENERATED VISITOR DECLARATIONS <<<

    MLIR_OpHandle program_op = MLIR_INVALID_HANDLE;

    void visit_Function(const ASR::Function_t &x);
    void visit_Program(const ASR::Program_t &x);
    void visit_TranslationUnit(const ASR::TranslationUnit_t &x);
};

} // namespace LCompilers

#endif // LFORTRAN_ASR_TO_ASR_DIALECT_H
