#!/usr/bin/env python3
"""
Generate ASR MLIR dialect artifacts from ASR.asdl (Design A: 1 constructor -> 1 asr.* op).

Outputs:
  - asr_dialect_schema.h
  - asr_dialect_api_generated.h
  - asr_dialect_lowering_dispatch.h
  - asr_dialect_print_helpers.h
  - asr_to_asr_dialect.h (generated declarations section)
  - asr_to_asr_dialect.cpp (generated implementations section)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import asdl

# ASDL types that are simple enum sums (not dialect ops).
# They appear as fields for other operations. 
SIMPLE_SUM_NAMES = {
    "cast_kind", "storage_type", "access", "intent", "deftype", "presence",
    "pass_attr", "abi", "codimension_type", "enumtype", "array_physical_type",
    "string_physical_type", "string_length_kind", "binop", "reduction_op",
    "logicalbinop", "cmpop", "integerboz", "arraybound", "arraystorage",
    "string_format_kind", "omp_region_type", "map_type", "schedule_type",
}

# Categories that produce dialect ops (top-level sum names in ASR.asdl).
OP_CATEGORIES = {"unit", "symbol", "stmt", "expr", "ttype"}

# Product-type sums that also become ops (records used as node payloads).
PRODUCT_OP_CATEGORIES = {
    "dimension", "codimension", "alloc_arg", "attribute", "attribute_arg",
    "call_arg", "reduction_expr", "tbind", "array_index", "do_loop_head",
    "case_stmt", "type_stmt", "rank_stmt", "require_instantiation", "omp_clause",
}

# Ops with ASR-dialect -> high-level MLIR lowering handlers (compile path).
# Keep this set aligned with what asr_dialect_lowering_handlers.c actually lowers;
# everything else remains dumpable in ASR dialect mode and fails before high MLIR.
COMPILE_SUPPORTED_OPS = {
    # Integer expressions (lower_expr_value / lower_expr_i1)
    "IntegerConstant", "IntegerBinOp", "IntegerCompare", "IntegerUnaryMinus",
    "Cast", "Var",
    # Narrow array subset (assignment + indexing)
    "ArrayItem", "ArrayConstant", "ArrayConstructor",
    # Program scaffolding
    "TranslationUnit", "Program", "Variable", "Assignment",
    "Return", "Print", "FileWrite", "DoLoop", "If", "ErrorStop",
}

# Fields omitted from dialect op storage (handled by emitter policy).
SKIP_FIELDS = {"location"}

# Pretty-print elision for asr.symbol.variable (field name -> rule tag).
# Keep empty so the dump shows the full variable attribute block (legacy format).
VARIABLE_FIELD_ELIDE = {}

PP_ELIDE_C_ENUM = {
    "always": "ASR_PP_ELIDE_ALWAYS",
    "i64_zero": "ASR_PP_ELIDE_I64_ZERO",
    "bool_false": "ASR_PP_ELIDE_BOOL_FALSE",
    "str_empty": "ASR_PP_ELIDE_STR_EMPTY",
}


def enum_pp_attr_category(asdl_type: str) -> str:
    """MLIR attribute dialect prefix for #asr.<category><kw>."""
    if asdl_type == "storage_type":
        return "storage"
    return snake_case(asdl_type)


CPP_KEYWORDS = {
    "inline", "static", "class", "virtual", "public", "private", "protected",
    "template", "operator", "new", "delete", "this", "friend", "register",
    "default",
    # unistd.h macros on Linux — must not be used as C++ identifiers
    "read", "write", "open", "close",
}

GENERATED_FILE_BANNER = "// Generated by asdl_to_asr_dialect.py — do not edit."


def generated_file_lines(*lines: str) -> list[str]:
    """Prefix fully generated file contents with the standard banner."""
    return [GENERATED_FILE_BANNER, ""] + list(lines)


def snake_case(name: str) -> str:
    out = []
    for i, ch in enumerate(name):
        if ch.isupper() and i > 0:
            out.append("_")
        out.append(ch.lower())
    return "".join(out)


def enum_kind(category: str, name: str) -> str:
    return f"ASR_DIALECT_OP_{category.upper()}_{name.upper()}"


def mlir_op_name(name: str) -> str:
    return f"asr.{snake_case(name)}"

def c_param_name(name: str) -> str:
    if name in CPP_KEYWORDS:
        return name + "_"
    return name

# Map ASDL field types to MLIR field kinds, in C++ Codes.
def field_kind(asdl_type: str, seq: bool, opt: bool) -> str:
    if asdl_type in SIMPLE_SUM_NAMES:
        base = "I64"
    elif asdl_type == "symbol":
        base = "SYMBOL_REF"
    elif asdl_type in ("expr", "stmt", "ttype", "node"):
        base = asdl_type.upper()
    elif asdl_type == "identifier":
        base = "IDENTIFIER"
    elif asdl_type == "string":
        base = "STRING"
    elif asdl_type == "int":
        base = "I64"
    elif asdl_type == "bool":
        base = "BOOL"
    elif asdl_type == "float":
        base = "F64"
    elif asdl_type == "void":
        base = "VOID"
    elif asdl_type.endswith("Type"):
        base = "I64"
    else:
        base = "OP"
    if seq:
        return f"ASR_FIELD_{base}_SEQ"
    if opt:
        return f"ASR_FIELD_{base}_OPT"
    return f"ASR_FIELD_{base}"

OP_HANDLE_SEQ_FIELD_KINDS = {
    "ASR_FIELD_OP_SEQ",
    "ASR_FIELD_NODE_SEQ",
    "ASR_FIELD_EXPR_SEQ",
    "ASR_FIELD_STMT_SEQ",
    "ASR_FIELD_SYMBOL_SEQ",
}


# Assign a ASR Value inside a Node to ASR Dialect Field structure.
def gen_field_assign(i: int, f: asdl.Field, param: str) -> list[str]:
    fname = f.name or f.type
    fk = field_kind(f.type, f.seq, f.opt)
    lines = [
        f"    fields[{i}].kind = {fk};",
        f"    fields[{i}].name = \"{fname}\";",
    ]
    if f.type in ("identifier", "string", "symbol"):
        lines.append(f"    fields[{i}].value.str = {param};")
    elif f.type == "bool":
        lines.append(f"    fields[{i}].value.b = {param};")
    elif f.type == "float":
        lines.append(f"    fields[{i}].value.f64 = {param};")
    elif f.type == "int" or is_enum_field(f.type) or f.type == "void":
        lines.append(f"    fields[{i}].value.i64 = {param};")
    elif f.type == "ttype":
        lines.append(f"    fields[{i}].value.type = {param};")
    elif f.seq and fk in OP_HANDLE_SEQ_FIELD_KINDS:
        lines.append(f"    fields[{i}].value.op_seq.items = {param};")
        lines.append(f"    fields[{i}].value.op_seq.n_items = n_{param};")
    else:
        lines.append(f"    fields[{i}].value.op = {param};")
    return lines


# Create a list of operations from the ASDL module.
def stored_dialect_fields(op: dict) -> list:
    """Fields stored on ASR dialect ops (may differ from ASR.asdl for mlir-new)."""
    if op["name"] == "ArrayConstant":
        # Do not store raw ASR heap pointers in dialect IR; use element expr ops.
        return [
            asdl.Field("expr", "elements", seq=True),
            asdl.Field("ttype", "type"),
            asdl.Field("arraystorage", "storage_format"),
        ]
    return [f for f in op["fields"] if f.name not in SKIP_FIELDS]


POLICY_HEADER_REL = "lfortran/asr_dialect_storage_policy.h"

ATTR_FIELD_KINDS = {
    "ASR_FIELD_I64", "ASR_FIELD_I64_OPT", "ASR_FIELD_F64", "ASR_FIELD_BOOL",
    "ASR_FIELD_BOOL_OPT", "ASR_FIELD_STRING", "ASR_FIELD_STRING_OPT",
    "ASR_FIELD_IDENTIFIER", "ASR_FIELD_IDENTIFIER_OPT", "ASR_FIELD_VOID",
    "ASR_FIELD_I64_SEQ", "ASR_FIELD_F64_SEQ", "ASR_FIELD_BOOL_SEQ",
    "ASR_FIELD_STRING_SEQ", "ASR_FIELD_IDENTIFIER_SEQ",
}

EXPR_OPERAND_FIELD_KINDS = {
    "ASR_FIELD_EXPR", "ASR_FIELD_OP", "ASR_FIELD_NODE",
}

EXPR_OPT_OPERAND_FIELD_KINDS = {
    "ASR_FIELD_EXPR_OPT", "ASR_FIELD_NODE_OPT", "ASR_FIELD_SYMBOL_OPT",
}

VARIADIC_OPERAND_FIELD_KINDS = {
    "ASR_FIELD_EXPR_SEQ", "ASR_FIELD_OP_SEQ", "ASR_FIELD_NODE_SEQ",
}

REGION_FIELD_KINDS = {
    "ASR_FIELD_STMT_SEQ", "ASR_FIELD_STMT", "ASR_FIELD_STMT_OPT",
}

SCOPE_OPS_WITH_METADATA = {"Program", "Function"}

# Dialect layout fields: not in ASR.asdl (synthetic or normalized storage).
DIALECT_LAYOUT_FIELDS: list[tuple[str, str, str]] = [
    ("Program", "metadata", "synthetic scope region (plan_mlir_asr_2 §3.1)"),
    ("Function", "metadata", "synthetic scope region (plan_mlir_asr_2 §3.1)"),
    ("ArrayConstant", "elements", "normalized from expr* (no raw ASR heap pointers)"),
]

# Visitor placeholders that must not back required stored fields.
PLACEHOLDER_EMITTER_FIELD_KINDS = {
    "ASR_FIELD_TTYPE_SEQ",
}

# Synthetic dialect fields (not in ASR.asdl) required by plan_mlir_asr_2.md §3.1.
SYNTHETIC_SCOPE_FIELDS: dict[str, list[tuple[str, str, str, str]]] = {
    "Program": [
        ("metadata", "ASR_STORAGE_REGION", "ASR_DIALECT_REGION_METADATA",
         "ASR_DIALECT_REGION_ELEM_METADATA"),
    ],
    "Function": [
        ("metadata", "ASR_STORAGE_REGION", "ASR_DIALECT_REGION_METADATA",
         "ASR_DIALECT_REGION_ELEM_METADATA"),
    ],
}


def field_id_enum(op_name: str, field_name: str) -> str:
    return f"ASR_DIALECT_FIELD_{op_name}_{field_name}"


def parse_storage_policy_overrides(policy_path: Path) -> dict[tuple[str, str], tuple[str, str, str]]:
    """Parse ASR_FIELD_STORAGE_OVERRIDES(X) entries from the policy header."""
    overrides: dict[tuple[str, str], tuple[str, str, str]] = {}
    if not policy_path.exists():
        return overrides
    text = policy_path.read_text(encoding="utf-8")
    for line in text.splitlines():
        line = line.strip()
        if not line.startswith("X("):
            continue
        if line.endswith("\\"):
            line = line[:-1].strip()
        if not line.endswith(")"):
            continue
        inner = line[2:-1]
        parts = [p.strip() for p in inner.split(",")]
        if len(parts) < 5:
            continue
        op_name, field_name, storage, region_kind, region_elem = parts[:5]
        overrides[(op_name, field_name)] = (storage, region_kind, region_elem)
    return overrides


def parse_region_layout(policy_path: Path) -> dict[tuple[str, str], int]:
    """Parse ASR_REGION_LAYOUT_LIST(X) entries from the policy header."""
    layouts: dict[tuple[str, str], int] = {}
    if not policy_path.exists():
        return layouts
    text = policy_path.read_text(encoding="utf-8")
    for line in text.splitlines():
        line = line.strip()
        if not line.startswith("X("):
            continue
        if line.endswith("\\"):
            line = line[:-1].strip()
        if not line.endswith(")"):
            continue
        inner = line[2:-1]
        parts = [p.strip() for p in inner.split(",")]
        if len(parts) != 3 or not parts[2].lstrip("-").isdigit():
            continue
        op_name, field_name, index_str = parts
        layouts[(op_name, field_name)] = int(index_str)
    return layouts


class FieldStoragePolicy:
    __slots__ = (
        "field_id", "storage", "region_kind", "region_element_kind",
        "operand_index", "region_index", "attr_index", "segment_attr",
    )

    def __init__(
        self,
        field_id: str,
        storage: str,
        region_kind: str = "ASR_DIALECT_REGION_NONE",
        region_element_kind: str = "ASR_DIALECT_REGION_ELEM_NONE",
        operand_index: int = -1,
        region_index: int = -1,
        attr_index: int = -1,
        segment_attr: str | None = None,
    ):
        self.field_id = field_id
        self.storage = storage
        self.region_kind = region_kind
        self.region_element_kind = region_element_kind
        self.operand_index = operand_index
        self.region_index = region_index
        self.attr_index = attr_index
        self.segment_attr = segment_attr


def default_field_storage(
        op_name: str, field_name: str, fk: str,
        category: str = "") -> FieldStoragePolicy:
    fid = field_id_enum(op_name, field_name)
    if fk in ATTR_FIELD_KINDS:
        return FieldStoragePolicy(fid, "ASR_STORAGE_ATTR")
    if fk == "ASR_FIELD_SYMBOL_REF":
        return FieldStoragePolicy(fid, "ASR_STORAGE_SYMBOL_REF_ATTR")
    if fk == "ASR_FIELD_SYMBOL_REF_SEQ":
        return FieldStoragePolicy(fid, "ASR_STORAGE_SYMBOL_REF_ARRAY_ATTR")
    if fk == "ASR_FIELD_TTYPE":
        return FieldStoragePolicy(fid, "ASR_STORAGE_RESULT_TYPE")
    if fk == "ASR_FIELD_TTYPE_OPT":
        return FieldStoragePolicy(fid, "ASR_STORAGE_TYPE_ATTR")
    if fk in EXPR_OPERAND_FIELD_KINDS:
        return FieldStoragePolicy(fid, "ASR_STORAGE_OPERAND")
    if fk in EXPR_OPT_OPERAND_FIELD_KINDS:
        if fk == "ASR_FIELD_STMT_OPT":
            return FieldStoragePolicy(
                fid, "ASR_STORAGE_OPTIONAL_REGION",
                "ASR_DIALECT_REGION_BODY", "ASR_DIALECT_REGION_ELEM_STMT")
        return FieldStoragePolicy(fid, "ASR_STORAGE_OPTIONAL_OPERAND")
    if fk in VARIADIC_OPERAND_FIELD_KINDS:
        elem = "ASR_DIALECT_REGION_ELEM_EXPR"
        if fk == "ASR_FIELD_OP_SEQ":
            elem = "ASR_DIALECT_REGION_ELEM_ANY"
        if fk == "ASR_FIELD_NODE_SEQ":
            elem = "ASR_DIALECT_REGION_ELEM_ANY"
        rk = "ASR_DIALECT_REGION_BODY"
        if field_name == "items":
            rk = "ASR_DIALECT_REGION_ITEMS"
        return FieldStoragePolicy(fid, "ASR_STORAGE_REGION", rk, elem)
    if fk in REGION_FIELD_KINDS or fk == "ASR_FIELD_NODE_SEQ":
        elem = "ASR_DIALECT_REGION_ELEM_STMT"
        if fk == "ASR_FIELD_NODE_SEQ":
            elem = "ASR_DIALECT_REGION_ELEM_ANY"
        rk = "ASR_DIALECT_REGION_BODY"
        if field_name == "orelse":
            rk = "ASR_DIALECT_REGION_ORELSE"
        if field_name == "items":
            rk = "ASR_DIALECT_REGION_ITEMS"
        return FieldStoragePolicy(fid, "ASR_STORAGE_REGION", rk, elem)
    if fk == "ASR_FIELD_SYMBOL":
        return FieldStoragePolicy(fid, "ASR_STORAGE_SYMBOL_REF_ATTR")
    if fk in ("ASR_FIELD_SYMBOL_REF_OPT", "ASR_FIELD_SYMBOL_REF_SEQ"):
        return FieldStoragePolicy(fid, "ASR_STORAGE_SYMBOL_REF_ATTR")
    if fk == "ASR_FIELD_TTYPE_SEQ":
        return FieldStoragePolicy(fid, "ASR_STORAGE_OMITTED")
    return FieldStoragePolicy(fid, "ASR_STORAGE_OMITTED")


def resolve_field_storage(
        op_name: str, field_name: str, fk: str,
        overrides: dict[tuple[str, str], tuple[str, str, str]],
        category: str = "") -> FieldStoragePolicy:
    key = (op_name, field_name)
    if key in overrides:
        storage, region_kind, region_elem = overrides[key]
        return FieldStoragePolicy(
            field_id_enum(op_name, field_name), storage, region_kind, region_elem)
    return default_field_storage(op_name, field_name, fk, category)


def assign_storage_indices(
        op_name: str,
        policies: list[tuple[str, FieldStoragePolicy]],
        region_layout: dict[tuple[str, str], int]) -> None:
    operand_idx = 0
    attr_idx = 0
    next_region = 0

    for fname, pol in policies:
        if pol.storage in ("ASR_STORAGE_ATTR", "ASR_STORAGE_SYMBOL_REF_ATTR",
                           "ASR_STORAGE_SYMBOL_REF_ARRAY_ATTR", "ASR_STORAGE_TYPE_ATTR"):
            pol.attr_index = attr_idx
            attr_idx += 1
        elif pol.storage in ("ASR_STORAGE_OPERAND", "ASR_STORAGE_OPTIONAL_OPERAND"):
            pol.operand_index = operand_idx
            operand_idx += 1
        elif pol.storage == "ASR_STORAGE_VARIADIC_OPERANDS":
            pol.operand_index = operand_idx
        elif pol.storage in ("ASR_STORAGE_REGION", "ASR_STORAGE_OPTIONAL_REGION"):
            key = (op_name, fname)
            if key in region_layout:
                pol.region_index = region_layout[key]
            else:
                pol.region_index = next_region
                next_region += 1


def compute_op_storage_policies(
        ops: list[dict],
        overrides: dict[tuple[str, str], tuple[str, str, str]],
        region_layout: dict[tuple[str, str], int]) -> dict[str, list[tuple[str, FieldStoragePolicy]]]:
    out: dict[str, list[tuple[str, FieldStoragePolicy]]] = {}
    for op in ops:
        stored = stored_dialect_fields(op)
        if not stored:
            continue
        policies: list[tuple[str, FieldStoragePolicy]] = []
        for f in stored:
            fname = f.name or f.type
            fk = field_kind(f.type, f.seq, f.opt)
            pol = resolve_field_storage(op["name"], fname, fk, overrides, op["category"])
            policies.append((fname, pol))
        for fname, storage, region_kind, region_elem in SYNTHETIC_SCOPE_FIELDS.get(
                op["name"], []):
            if any(n == fname for n, _ in policies):
                continue
            pol = FieldStoragePolicy(
                field_id_enum(op["name"], fname),
                storage, region_kind, region_elem)
            policies.append((fname, pol))
        assign_storage_indices(op["name"], policies, region_layout)
        out[op["kind"]] = policies
    return out


def dialect_layout_field_names() -> set[tuple[str, str]]:
    return {(op, field) for op, field, _note in DIALECT_LAYOUT_FIELDS}


def validate_policy_coverage(
        ops: list[dict],
        overrides: dict[tuple[str, str], tuple[str, str, str]],
        all_policies: dict[str, list[tuple[str, FieldStoragePolicy]]]) -> None:
    known: set[tuple[str, str]] = set()
    for op in ops:
        for f in stored_dialect_fields(op):
            known.add((op["name"], f.name or f.type))
        for fname, _storage, _rk, _re in SYNTHETIC_SCOPE_FIELDS.get(op["name"], []):
            known.add((op["name"], fname))
    for key in overrides:
        if key not in known:
            raise SystemExit(
                f"asdl_to_asr_dialect: unknown policy override {key[0]}.{key[1]}")
    for op in ops:
        stored = stored_dialect_fields(op)
        if not stored and op["name"] not in SYNTHETIC_SCOPE_FIELDS:
            continue
        policies = all_policies.get(op["kind"], [])
        if not policies:
            raise SystemExit(
                f"asdl_to_asr_dialect: missing storage policy for {op['name']}")
        pol_by_name = {n: p for n, p in policies}
        for f in stored:
            fname = f.name or f.type
            fk = field_kind(f.type, f.seq, f.opt)
            pres = "ASR_FIELD_OPTIONAL" if f.opt else "ASR_FIELD_REQUIRED"
            pol = pol_by_name.get(fname)
            if not pol:
                raise SystemExit(
                    f"asdl_to_asr_dialect: no policy for stored field "
                    f"{op['name']}.{fname}")
            if (pol.storage != "ASR_STORAGE_OMITTED" and
                    fk in PLACEHOLDER_EMITTER_FIELD_KINDS):
                raise SystemExit(
                    f"asdl_to_asr_dialect: field {op['name']}.{fname} "
                    f"uses placeholder emitter ({fk}) but storage is not OMITTED")


def gen_storage_merged_h(
        ops: list[dict],
        all_policies: dict[str, list[tuple[str, FieldStoragePolicy]]]) -> str:
    lines = generated_file_lines(
        "// Exhaustive merged storage policy (defaults + header overrides).",
        "// Regenerate with asdl_to_asr_dialect.py; do not edit.",
        "",
        "#pragma once",
        "",
        "#define ASR_FIELD_STORAGE_MERGED(X) \\",
    )
    entries: list[str] = []
    for op in ops:
        policies = all_policies.get(op["kind"], [])
        if not policies:
            continue
        for fname, pol in policies:
            entries.append(
                f"    X({op['name']}, {fname}, {pol.storage}, "
                f"{pol.region_kind}, {pol.region_element_kind}) \\")
    lines.extend(sorted(entries))
    lines.append("")
    return "\n".join(lines)


def gen_dialect_layout_h() -> str:
    lines = generated_file_lines(
        "#pragma once",
        "",
        "// Fields stored on dialect ops but not present in ASR.asdl.",
        "#define ASR_DIALECT_LAYOUT_FIELDS(X) \\",
    )
    for op_name, field_name, note in DIALECT_LAYOUT_FIELDS:
        lines.append(f"    /* {note} */ \\")
        lines.append(f"    X({op_name}, {field_name}) \\")
    lines.append("")
    return "\n".join(lines)


def schema_field_entries(op: dict, policies: list[tuple[str, FieldStoragePolicy]]) -> list[tuple]:
    """ASDL fields plus synthetic scope fields for schema/accessor emission."""
    stored = stored_dialect_fields(op)
    pol_by_name = {n: p for n, p in policies}
    entries: list[tuple] = []
    seen: set[str] = set()
    for f in stored:
        fname = f.name or f.type
        fk = field_kind(f.type, f.seq, f.opt)
        pres = "ASR_FIELD_OPTIONAL" if f.opt else "ASR_FIELD_REQUIRED"
        pol = pol_by_name.get(fname)
        if not pol:
            pol = default_field_storage(op["name"], fname, fk, op["category"])
        entries.append((fname, fk, pres, pol))
        seen.add(fname)
    for fname, _storage, _rk, _re in SYNTHETIC_SCOPE_FIELDS.get(op["name"], []):
        if fname in seen:
            continue
        pol = pol_by_name.get(fname)
        if not pol:
            continue
        entries.append((fname, "ASR_FIELD_OP", "ASR_FIELD_REQUIRED", pol))
    return entries


def op_region_count(_op_name: str, policies: list[tuple[str, FieldStoragePolicy]]) -> int:
    max_idx = -1
    for _fname, pol in policies:
        if pol.storage in ("ASR_STORAGE_REGION", "ASR_STORAGE_OPTIONAL_REGION"):
            max_idx = max(max_idx, pol.region_index)
    return max_idx + 1 if max_idx >= 0 else 0


def _gen_ids_lines(ops: list[dict], all_policies: dict) -> list[str]:
    """Field ID enum (body only, emitted inside asr_dialect_schema.h)."""
    lines = [
        "typedef enum {",
        "    ASR_DIALECT_FIELD_INVALID = 0,",
    ]
    field_ids: list[str] = []
    for op in ops:
        policies = all_policies.get(op["kind"], [])
        if policies:
            for fname, _fk, _pres, _pol in schema_field_entries(op, policies):
                field_ids.append(field_id_enum(op["name"], fname))
        else:
            for f in stored_dialect_fields(op):
                fname = f.name or f.type
                field_ids.append(field_id_enum(op["name"], fname))
    for fid in sorted(set(field_ids)):
        lines.append(f"    {fid},")
    lines.extend([
        "    ASR_DIALECT_FIELD_COUNT",
        "} ASR_DialectFieldId;",
        "",
    ])
    return lines


def c_accessor_name(op_name: str, field_name: str) -> str:
    return f"ASR_{op_name}{field_name[0].upper()}{field_name[1:]}"


def _gen_accessors_lines(ops: list[dict], all_policies: dict) -> list[str]:
    """Typed field getters (body only, emitted inside asr_dialect_api_generated.h)."""
    lines = [
        "static inline MLIR_OpHandle asr_operand_defining_op(MLIR_ValueHandle v) {",
        "    if (v == MLIR_INVALID_HANDLE) {",
        "        return MLIR_INVALID_HANDLE;",
        "    }",
        "    return MLIR_GetValueDefiningOp(v);",
        "}",
        "",
    ]

    for op in ops:
        op_name = op["name"]
        policies = all_policies.get(op["kind"], [])
        for fname, pol in policies:
            acc = c_accessor_name(op_name, fname)
            if pol.storage in ("ASR_STORAGE_OPERAND", "ASR_STORAGE_OPTIONAL_OPERAND"):
                lines.append(f"static inline MLIR_ValueHandle {acc}(MLIR_OpHandle op) {{")
                if pol.operand_index >= 0:
                    lines.append(
                        f"    if (MLIR_GetOpNumOperands(op) > (size_t){pol.operand_index}) {{")
                    lines.append(
                        f"        return MLIR_GetOpOperand(op, (size_t){pol.operand_index});")
                    lines.append("    }")
                lines.append("    return MLIR_INVALID_HANDLE;")
                lines.append("}")
                lines.append("")
                op_acc = f"{acc}Op"
                lines.append(f"static inline MLIR_OpHandle {op_acc}(MLIR_OpHandle op) {{")
                lines.append(f"    return asr_operand_defining_op({acc}(op));")
                lines.append("}")
                lines.append("")
            elif pol.storage == "ASR_STORAGE_SYMBOL_REF_ATTR":
                lines.append(f"static inline string {acc}(MLIR_OpHandle op) {{")
                lines.append(f"    return asr_get_field_str(op, \"{fname}\");")
                lines.append("}")
                lines.append("")
            elif pol.storage in ("ASR_STORAGE_REGION", "ASR_STORAGE_OPTIONAL_REGION"):
                title = fname[0].upper() + fname[1:]
                fn = f"ASR_{op_name}Get{title}Region"
                existing = [l.split("(")[0].split()[-1]
                            for l in lines if l.startswith("static inline MLIR_RegionHandle")]
                if fn not in existing:
                    lines.append(f"static inline MLIR_RegionHandle {fn}(MLIR_OpHandle op) {{")
                    if pol.region_index >= 0:
                        lines.append(
                            f"    if (MLIR_GetOpNumRegions(op) > (size_t){pol.region_index}) {{")
                        lines.append(
                            f"        return MLIR_GetOpRegion(op, (size_t){pol.region_index});")
                        lines.append("    }")
                    lines.append("    return MLIR_INVALID_HANDLE;")
                    lines.append("}")
                    lines.append("")

    return lines


def _gen_api_creators_lines(ops: list[dict]) -> list[str]:
    """ASR_Create*Op wrappers (body only, needs asr_dialect_api.h types)."""
    lines: list[str] = []
    for op in ops:
        stored = stored_dialect_fields(op)
        params = ["MLIR_Context *ctx", "MLIR_LocationHandle loc"]
        for f in stored:
            fname = c_param_name(f.name or f.type)
            if f.seq and f.type in ("expr", "stmt", "node"):
                params.append(f"MLIR_OpHandle *{fname}")
                params.append(f"size_t n_{fname}")
            elif f.type in ("expr", "stmt", "node"):
                params.append(f"MLIR_OpHandle {fname}")
            elif f.type == "symbol":
                params.append(f"ASR_SymbolRef {fname}")
            elif f.type == "ttype":
                params.append(f"MLIR_TypeHandle {fname}")
            elif f.type in ("identifier", "string"):
                params.append(f"string {fname}")
            elif f.type == "int" or is_enum_field(f.type):
                params.append(f"int64_t {fname}")
            elif f.type == "bool":
                params.append(f"bool {fname}")
            elif f.type == "float":
                params.append(f"double {fname}")
            elif f.seq:
                params.append(f"MLIR_OpHandle *{fname}")
                params.append(f"size_t n_{fname}")
            else:
                params.append(f"MLIR_OpHandle {fname}")
        fn = f"ASR_Create{op['name']}Op"
        lines.append(f"static inline MLIR_OpHandle {fn}(")
        lines.append("        " + ",\n        ".join(params) + ") {")
        n = len(stored)
        if n == 0:
            lines.append("    (void)ctx; (void)loc;")
            lines.append(
                f"    return ASR_DialectCreateOp(ctx, {op['kind']}, loc, NULL, 0);")
        else:
            lines.append(f"    ASR_DialectField fields[{n}] = {{}};")
            for i, f in enumerate(stored):
                param = c_param_name(f.name or f.type)
                lines.extend(gen_field_assign(i, f, param))
            lines.append(
                f"    return ASR_DialectCreateOp(ctx, {op['kind']}, loc, fields, {n});")
        lines.append("}")
        lines.append("")
    return lines


def gen_api_generated_h(ops: list[dict], all_policies: dict) -> str:
    """Field accessors + ASR_Create*Op wrappers."""
    lines = generated_file_lines(
        "#ifndef ASR_DIALECT_API_GENERATED_ACCESSORS_H",
        "#define ASR_DIALECT_API_GENERATED_ACCESSORS_H",
        "",
        "#include <mlir_api.h>",
        "#include \"asr_dialect_storage.h\"",
        "",
        "#ifndef ASR_DIALECT_HAS_NATIVE_FIELD_STORAGE",
        "#define ASR_DIALECT_HAS_NATIVE_FIELD_STORAGE 1",
        "#endif",
        "",
    )
    lines.extend(_gen_accessors_lines(ops, all_policies))
    lines.extend([
        "",
        "#endif  /* ASR_DIALECT_API_GENERATED_ACCESSORS_H */",
        "",
        "#ifdef ASR_DIALECT_API_GENERATED_INCLUDE_CREATORS",
        "#ifndef ASR_DIALECT_API_GENERATED_CREATORS_H",
        "#define ASR_DIALECT_API_GENERATED_CREATORS_H",
        "",
        "// Include Create* wrappers from C/C++ translation units only "
        "(not asr_dialect_api.h).",
        "#include \"asr_dialect_api.h\"",
        "",
    ])
    lines.extend(_gen_api_creators_lines(ops))
    lines.extend([
        "",
        "#endif  /* ASR_DIALECT_API_GENERATED_CREATORS_H */",
        "#endif  /* ASR_DIALECT_API_GENERATED_INCLUDE_CREATORS */",
    ])
    return "\n".join(lines) + "\n"


def collect_ops(mod: asdl.Module) -> list[dict]:
    ops = []
    # Ignore simple no-operation enum types, like intent.
    for dfn in mod.dfns:
        cat = dfn.name
        val = dfn.value
        if isinstance(val, asdl.Product):
            ops.append({
                "category": cat,
                "name": cat,
                "fields": val.fields,
                "kind": enum_kind(cat, cat),
                "mlir_name": mlir_op_name(cat),
            })
        elif cat in OP_CATEGORIES or cat in PRODUCT_OP_CATEGORIES:
            for cons in val.types:
                ops.append({
                    "category": cat,
                    "name": cons.name,
                    "fields": cons.fields,
                    "kind": enum_kind(cat, cons.name),
                    "mlir_name": mlir_op_name(cons.name),
                })
    ops.sort(key=lambda o: (o["category"], o["name"]))
    return ops


def collect_simple_enums(mod: asdl.Module) -> dict[str, list[str]]:
    enums = {}
    for dfn in mod.dfns:
        # Collect simple enum types, like binop, intent etc, which dont have
        # an ASR Dialect operation (example: intent).
        if dfn.name in SIMPLE_SUM_NAMES and isinstance(dfn.value, asdl.Sum):
            enums[dfn.name] = [c.name for c in dfn.value.types]
    return enums


def gen_schema_h(ops: list[dict], all_policies: dict) -> str:
    cat_map = {
        "unit": "ASR_DIALECT_CATEGORY_UNIT",
        "symbol": "ASR_DIALECT_CATEGORY_SYMBOL",
        "stmt": "ASR_DIALECT_CATEGORY_STMT",
        "expr": "ASR_DIALECT_CATEGORY_EXPR",
        "ttype": "ASR_DIALECT_CATEGORY_TTYPE",
    }
    lines = generated_file_lines(
        "#pragma once",
        "",
        "#include <stddef.h>",
        "",
        '#include "lfortran/asr_dialect_storage_policy.h"',
        "",
    )
    lines.extend(_gen_ids_lines(ops, all_policies))
    lines.extend([
        "typedef enum {",
        "    ASR_DIALECT_OP_INVALID = 0,",
    ])
    for op in ops:
        lines.append(f"    {op['kind']},")
    lines.extend([
        "    ASR_DIALECT_OP_COUNT",
        "} ASR_DialectOpKind;",
        "",
        "typedef enum {",
        "    ASR_DIALECT_CATEGORY_UNIT,",
        "    ASR_DIALECT_CATEGORY_SYMBOL,",
        "    ASR_DIALECT_CATEGORY_STMT,",
        "    ASR_DIALECT_CATEGORY_EXPR,",
        "    ASR_DIALECT_CATEGORY_TTYPE,",
        "    ASR_DIALECT_CATEGORY_PRODUCT,",
        "} ASR_DialectCategory;",
        "",
        "typedef enum {",
        "    ASR_FIELD_I64, ASR_FIELD_F64, ASR_FIELD_BOOL,",
        "    ASR_FIELD_STRING, ASR_FIELD_IDENTIFIER,",
        "    ASR_FIELD_SYMBOL_REF, ASR_FIELD_SYMBOL_REF_OPT, ASR_FIELD_SYMBOL_REF_SEQ,",
        "    ASR_FIELD_EXPR, ASR_FIELD_STMT, ASR_FIELD_SYMBOL,",
        "    ASR_FIELD_TTYPE, ASR_FIELD_NODE, ASR_FIELD_OP,",
        "    ASR_FIELD_VOID, ASR_FIELD_I64_SEQ, ASR_FIELD_F64_SEQ,",
        "    ASR_FIELD_BOOL_SEQ, ASR_FIELD_STRING_SEQ,",
        "    ASR_FIELD_IDENTIFIER_SEQ, ASR_FIELD_EXPR_SEQ,",
        "    ASR_FIELD_STMT_SEQ, ASR_FIELD_SYMBOL_SEQ,",
        "    ASR_FIELD_TTYPE_SEQ, ASR_FIELD_NODE_SEQ, ASR_FIELD_OP_SEQ,",
        "    ASR_FIELD_EXPR_OPT, ASR_FIELD_STMT_OPT, ASR_FIELD_SYMBOL_OPT,",
        "    ASR_FIELD_TTYPE_OPT, ASR_FIELD_NODE_OPT, ASR_FIELD_I64_OPT,",
        "    ASR_FIELD_F64_OPT, ASR_FIELD_STRING_OPT,",
        "    ASR_FIELD_IDENTIFIER_OPT, ASR_FIELD_BOOL_OPT,",
        "} ASR_DialectFieldKind;",
        "",
        "typedef enum { ASR_FIELD_REQUIRED, ASR_FIELD_OPTIONAL } ASR_FieldPresence;",
        "",
        "typedef struct {",
        "    const char *name;",
        "    ASR_DialectFieldKind kind;",
        "    ASR_FieldPresence presence;",
        "    ASR_DialectFieldId field_id;",
        "    ASR_FieldStorageKind storage;",
        "    ASR_DialectRegionKind region_kind;",
        "    ASR_DialectRegionElementKind region_element_kind;",
        "    int operand_index;",
        "    int region_index;",
        "    int attr_index;",
        "    const char *segment_attr;",
        "} ASR_DialectFieldDesc;",
        "",
        "typedef struct {",
        "    ASR_DialectOpKind kind;",
        "    ASR_DialectCategory category;",
        "    const char *asr_name;",
        "    const char *mlir_name;",
        "    size_t n_fields;",
        "    const ASR_DialectFieldDesc *fields;",
        "    size_t n_regions;",
        "} ASR_DialectOpSchema;",
        "",
    ])
    for op in ops:
        policies = all_policies.get(op["kind"], [])
        entries = schema_field_entries(op, policies) if policies else []
        if not entries:
            continue
        lines.append(f"static const ASR_DialectFieldDesc {op['kind']}_FIELDS[] = {{")
        for fname, fk, pres, pol in entries:
            seg = f'"{pol.segment_attr}"' if pol.segment_attr else "NULL"
            lines.append(
                f'    {{"{fname}", {fk}, {pres}, {pol.field_id}, '
                f"{pol.storage}, {pol.region_kind}, {pol.region_element_kind}, "
                f"{pol.operand_index}, {pol.region_index}, {pol.attr_index}, {seg}}},"
            )
        lines.append("};")
        lines.append("")

    lines.append("static const ASR_DialectOpSchema ASR_DIALECT_SCHEMA[] = {")
    for op in ops:
        policies = all_policies.get(op["kind"], [])
        entries = schema_field_entries(op, policies) if policies else []
        cat = cat_map.get(op["category"], "ASR_DIALECT_CATEGORY_PRODUCT")
        fields_ref = f"{op['kind']}_FIELDS" if entries else "NULL"
        n_regions = op_region_count(op["name"], policies) if policies else 0
        lines.append("    {")
        lines.append(f"        .kind = {op['kind']},")
        lines.append(f"        .category = {cat},")
        lines.append(f'        .asr_name = "{op["name"]}",')
        lines.append(f'        .mlir_name = "{op["mlir_name"]}",')
        lines.append(f"        .n_fields = {len(entries)},")
        lines.append(f"        .fields = {fields_ref},")
        lines.append(f"        .n_regions = {n_regions},")
        lines.append("    },")
    lines.extend([
        "};",
        "",
        "static const size_t ASR_DIALECT_SCHEMA_COUNT =",
        "    sizeof(ASR_DIALECT_SCHEMA) / sizeof(ASR_DIALECT_SCHEMA[0]);",
        "",
        "typedef struct {",
        "    const char *mlir_name;",
        "    ASR_DialectOpKind kind;",
        "} ASR_DialectSchemaNameEntry;",
        "",
        "static const ASR_DialectSchemaNameEntry ASR_DIALECT_SCHEMA_BY_NAME[] = {",
    ])
    name_entries = []
    for op in ops:
        name_entries.append((op["mlir_name"], op["kind"]))
    for mlir_name, kind in sorted(name_entries, key=lambda e: e[0]):
        lines.append(f'    {{"{mlir_name}", {kind}}},')
    lines.extend([
        "};",
        "",
        "static const size_t ASR_DIALECT_SCHEMA_NAME_COUNT =",
        "    sizeof(ASR_DIALECT_SCHEMA_BY_NAME) / "
        "sizeof(ASR_DIALECT_SCHEMA_BY_NAME[0]);",
        "",
    ])
    return "\n".join(lines)


def asr_member(field: asdl.Field) -> str:
    if field.name:
        return f"m_{field.name}"
    return field.type


def asr_count_member(field: asdl.Field) -> str:
    assert field.name
    return f"n_{field.name}"


def is_enum_field(asdl_type: str) -> bool:
    return asdl_type in SIMPLE_SUM_NAMES or asdl_type.endswith("Type")


def cpp_emit_field(field: asdl.Field) -> str:
    name = field.name
    asdl_type = field.type
    if name in SKIP_FIELDS:
        return ""
    fname = c_param_name(name or asdl_type)
    member = asr_member(field)
    if asdl_type == "expr":
        if field.seq:
            count = asr_count_member(field)
            return (f"        size_t n_{fname} = x.{count};\n"
                    f"        MLIR_OpHandle *{fname} = emit_expr_op_array(x.{member}, n_{fname});")
        if field.opt:
            return (f"        MLIR_ValueHandle {fname} = MLIR_INVALID_HANDLE;\n"
                    f"        if (x.{member}) {{ {fname} = emit_expr(*x.{member}); }}")
        return f"        MLIR_ValueHandle {fname} = emit_expr(*x.{member});"
    if asdl_type == "stmt":
        if field.seq:
            count = asr_count_member(field)
            return (f"        size_t n_{fname} = x.{count};\n"
                    f"        MLIR_OpHandle *{fname} = emit_stmt_op_array(x.{member}, n_{fname}, &n_{fname});")
        if field.opt:
            return (f"        MLIR_ValueHandle {fname} = MLIR_INVALID_HANDLE;\n"
                    f"        if (x.{member}) {{ {fname} = emit_stmt(*x.{member}); }}")
        return f"        MLIR_ValueHandle {fname} = emit_stmt(*x.{member});"
    if asdl_type == "symbol":
        if field.seq:
            return f"        string {fname} = emit_symbol_seq_ref(x.{member}, x.{asr_count_member(field)});"
        if field.opt:
            return (f"        string {fname} = str_lit(\"\");\n"
                    f"        if (x.{member}) {{ {fname} = emit_symbol_ref(*x.{member}); }}")
        return f"        string {fname} = emit_symbol_ref(*x.{member});"
    if asdl_type == "ttype":
        if field.seq:
            return f"        MLIR_TypeHandle {fname} = emit_type_seq_value(x.{member}, x.{asr_count_member(field)});"
        if field.opt:
            return (f"        MLIR_TypeHandle {fname} = MLIR_INVALID_HANDLE;\n"
                    f"        if (x.{member}) {{ {fname} = convert_type(*x.{member}); }}")
        return f"        MLIR_TypeHandle {fname} = convert_type(*x.{member});"
    if asdl_type == "identifier":
        if field.seq:
            return (f"        string {fname} = emit_identifier_seq("
                    f"x.{member}, x.{asr_count_member(field)});")
        return f"        string {fname} = asr_cstr(x.{member});"
    if asdl_type == "string":
        if field.opt:
            return (f"        string {fname} = str_lit(\"\");\n"
                    f"        if (x.{member}) {{ {fname} = asr_cstr(x.{member}); }}")
        return f"        string {fname} = asr_cstr(x.{member});"
    if asdl_type == "int":
        return f"        int64_t {fname} = x.{member};"
    if asdl_type == "bool":
        return f"        bool {fname} = x.{member};"
    if asdl_type == "float":
        return f"        double {fname} = x.{member};"
    if asdl_type == "void":
        return f"        int64_t {fname} = (int64_t)x.{member};"
    if is_enum_field(asdl_type):
        return f"        int64_t {fname} = (int64_t)x.{member};"
    if asdl_type == "array_index" and field.seq:
        count = asr_count_member(field)
        return (f"        size_t n_{fname} = x.{count};\n"
                f"        MLIR_OpHandle *{fname} = emit_array_index_op_array(x.{member}, n_{fname});")
    if field.seq and field_kind(asdl_type, True, field.opt) == "ASR_FIELD_OP_SEQ":
        count = asr_count_member(field)
        return (f"        size_t n_{fname} = x.{count};\n"
                f"        MLIR_OpHandle *{fname} = emit_product_op_array(x.{member}, n_{fname});")
    if field.seq:
        count = asr_count_member(field)
        return (f"        size_t n_{fname} = x.{count};\n"
                f"        MLIR_ValueHandle {fname} = MLIR_INVALID_HANDLE;\n"
                f"        (void)x.{member};")
    emit_fn = PRODUCT_EMIT_CPP.get(asdl_type)
    if emit_fn:
        if field.opt:
            return (f"        MLIR_ValueHandle {fname} = MLIR_INVALID_HANDLE;\n"
                    f"        if (x.{member}) {{ {fname} = {emit_fn}(*x.{member}); }}")
        return f"        MLIR_ValueHandle {fname} = {emit_fn}(x.{member});"
    if field.opt:
        return (f"        MLIR_ValueHandle {fname} = MLIR_INVALID_HANDLE;\n"
                f"        if (x.{member}) {{ {fname} = emit_product_value(x.{member}); }}")
    return f"        MLIR_ValueHandle {fname} = emit_product_value(x.{member});"


# Hand-written in asr_to_asr_dialect.cpp (module layout + multi-stmt do bodies).
VISITOR_DECL_START = "// >>> GENERATED VISITOR DECLARATIONS >>>"
VISITOR_DECL_END = "// <<< END GENERATED VISITOR DECLARATIONS <<<"
VISITOR_IMPL_START = "// >>> GENERATED VISITOR IMPLEMENTATIONS >>>"
VISITOR_IMPL_END = "// <<< END GENERATED VISITOR IMPLEMENTATIONS <<<"

SKIP_VISITOR_OPS = {
    "Program", "TranslationUnit", "DoLoop", "If", "WhileLoop", "Print",
    "FileWrite", "Variable", "Var", "StringFormat", "ArrayConstructor",
    "ArrayItem", "ArrayConstant",
}

# Embedded ASR products emitted by helpers in asr_to_asr_dialect.cpp.
PRODUCT_EMIT_CPP = {
    "do_loop_head": "emit_do_loop_head",
    "array_index": "emit_array_index",
}


def visitor_create_args(fields: list[asdl.Field]) -> list[str]:
    """Build ASR_Create*Op argument list matching generated API signatures."""
    args = []
    for f in fields:
        fname = c_param_name(f.name or f.type)
        fk = field_kind(f.type, f.seq, f.opt)
        # Product/node sequences use MLIR_OpHandle* + count in generated API.
        if f.seq and fk in (
            "ASR_FIELD_OP_SEQ",
            "ASR_FIELD_NODE_SEQ",
            "ASR_FIELD_EXPR_SEQ",
            "ASR_FIELD_STMT_SEQ",
        ):
            args.append(fname)
            args.append(f"n_{fname}")
            continue
        args.append(fname)
    return args


def gen_visitor_declarations(ops: list[dict]) -> str:
    lines = generated_file_lines()
    for op in ops:
        if op["category"] not in ("expr", "stmt"):
            continue
        if op["name"] in SKIP_VISITOR_OPS:
            continue
        lines.append(
            f"    void visit_{op['name']}(const ASR::{op['name']}_t &x);")
    if len(lines) == 2:
        lines.append("")
    return "\n".join(lines) + "\n"


def gen_visitor_implementations(ops: list[dict]) -> str:
    lines = generated_file_lines()
    for op in ops:
        if op["category"] not in ("expr", "stmt"):
            continue
        if op["name"] in SKIP_VISITOR_OPS:
            continue
        stored = [f for f in op["fields"] if f.name not in SKIP_FIELDS]
        lines.append(f"void ASRToAsrDialectVisitor::visit_{op['name']}(const ASR::{op['name']}_t &x) {{")
        for f in stored:
            code = cpp_emit_field(f)
            if code:
                # Drop class-body indent from helper snippets.
                lines.append(code[4:] if code.startswith("        ") else code)
        lines.append("    MLIR_LocationHandle op_loc = loc(x.base.base.loc);")
        fn = f"ASR_Create{op['name']}Op"
        create_args = visitor_create_args(stored)
        if stored:
            lines.append(
                f"    last_value = {fn}(&ctx, op_loc, {', '.join(create_args)});")
        else:
            lines.append(f"    last_value = {fn}(&ctx, op_loc);")
        if op["category"] == "stmt":
            lines.append("    append_current_stmt(last_value);")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def replace_marked_section(path: Path, start: str, end: str, content: str) -> None:
    text = path.read_text(encoding="utf-8")
    start_idx = text.find(start)
    end_idx = text.find(end)
    if start_idx < 0 or end_idx < 0 or end_idx < start_idx:
        raise RuntimeError(f"marker pair not found in {path}")
    end_idx += len(end)
    new_text = text[:start_idx] + start + "\n" + content + end + text[end_idx:]
    path.write_text(new_text, encoding="utf-8")


def check_marked_section(path: Path, start: str, end: str, expected: str) -> bool:
    if not path.exists():
        print(f"MISSING: {path}", file=sys.stderr)
        return False
    text = path.read_text(encoding="utf-8")
    start_idx = text.find(start)
    end_idx = text.find(end)
    if start_idx < 0 or end_idx < 0 or end_idx < start_idx:
        print(f"MARKERS MISSING: {path}", file=sys.stderr)
        return False
    start_idx += len(start)
    existing = text[start_idx:end_idx]
    if existing != "\n" + expected:
        print(f"STALE: {path} ({start})", file=sys.stderr)
        return False
    return True


def update_visitor_sources(codegen_dir: Path, ops: list[dict]) -> None:
    decls = gen_visitor_declarations(ops)
    impls = gen_visitor_implementations(ops)
    replace_marked_section(
        codegen_dir / "asr_to_asr_dialect.h",
        VISITOR_DECL_START, VISITOR_DECL_END, decls)
    replace_marked_section(
        codegen_dir / "asr_to_asr_dialect.cpp",
        VISITOR_IMPL_START, VISITOR_IMPL_END, impls)
    print(f"Updated {codegen_dir / 'asr_to_asr_dialect.h'}")
    print(f"Updated {codegen_dir / 'asr_to_asr_dialect.cpp'}")


def check_visitor_sources(codegen_dir: Path, ops: list[dict]) -> bool:
    decls = gen_visitor_declarations(ops)
    impls = gen_visitor_implementations(ops)
    ok = check_marked_section(
        codegen_dir / "asr_to_asr_dialect.h",
        VISITOR_DECL_START, VISITOR_DECL_END, decls)
    ok = check_marked_section(
        codegen_dir / "asr_to_asr_dialect.cpp",
        VISITOR_IMPL_START, VISITOR_IMPL_END, impls) and ok
    return ok


def gen_lowering_dispatch_h(ops: list[dict]) -> str:
    lines = generated_file_lines(
        "#pragma once",
        "",
        "#include \"asr_dialect_api.h\"",
        "",
        "/* Lowering handlers exist only for COMPILE_SUPPORTED_OPS (see asdl_to_asr_dialect.py). */",
        "",
    )
    for op in ops:
        if op["name"] in COMPILE_SUPPORTED_OPS:
            handler = f"ASR_Lower{op['name']}"
            lines.append(
                f"extern bool {handler}(ASR_LoweringContext *lc, MLIR_OpHandle op);")
    lines.extend([
        "",
        "static inline bool ASR_DialectLowerOneOp(",
        "        ASR_LoweringContext *ctx, MLIR_OpHandle op) {",
        "    ASR_DialectOpKind kind = ASR_DialectGetOpKind(op);",
        "    switch (kind) {",
    ])
    for op in ops:
        if op["name"] in COMPILE_SUPPORTED_OPS:
            handler = f"ASR_Lower{op['name']}"
            lines.append(f"    case {op['kind']}:")
            lines.append(f"        return {handler}(ctx, op);")
    lines.extend([
        "    default:",
        '        return ASR_LowerUnsupported(ctx, op, "ASR dialect op has no lowering yet");',
        "    }",
        "}",
        "",
    ])
    return "\n".join(lines)


def _gen_enum_print_lines(enums: dict[str, list[str]]) -> list[str]:
    """Enum name tables and lookup helpers (body only, no file header)."""
    lines = [
        "static inline const char *asr_enum_name_or_unknown(",
        "        const char *const *names, size_t n_names, int64_t v) {",
        "    if (v >= 0 && (size_t)v < n_names) {",
        "        return names[(size_t)v];",
        "    }",
        "    return NULL;",
        "}",
        "",
    ]
    for enum_name, variants in sorted(enums.items()):
        c_names = f"ASR_ENUM_{enum_name.upper()}_NAMES"
        kw = [snake_case(v) for v in variants]
        lines.append(f"static const char *const {c_names}[] = {{")
        for k in kw:
            lines.append(f'    "{k}",')
        lines.append("};")
        lines.append(f"static const size_t {c_names}_COUNT = {len(kw)};")
        lines.append("")
        fn = f"asr_enum_{snake_case(enum_name)}_name"
        lines.append(f"static inline const char *{fn}(int64_t v) {{")
        lines.append(
            f"    return asr_enum_name_or_unknown({c_names}, {c_names}_COUNT, v);")
        lines.append("}")
        lines.append("")
    return lines


def collect_variable_enum_pp_fields(variable_op: dict | None) -> list[tuple[str, str]]:
    """(field name, ASDL enum type) for Variable I64 fields backed by simple sums."""
    if not variable_op:
        return []
    out: list[tuple[str, str]] = []
    for f in variable_op["fields"]:
        if not f.name or f.name in SKIP_FIELDS:
            continue
        if f.seq:
            continue
        if f.type in SIMPLE_SUM_NAMES:
            out.append((f.name, f.type))
    return sorted(out)


def gen_variable_scalar_field_printer(variable_op: dict | None) -> list[str]:
    """Emit scalar Variable field line formatter for legacy pretty print."""
    lines = [
        "",
        "/* Format one scalar Variable declaration field (legacy dump line). */",
        "static inline bool asr_pp_format_variable_scalar_field(",
        "        MLIR_OpHandle op, const char *field, char *buf, size_t bufsz) {",
        "    if (!field || !buf || bufsz == 0) {",
        "        return false;",
        "    }",
    ]
    if not variable_op:
        lines.extend([
            "    (void)op;",
            "    return false;",
            "}",
        ])
        return lines

    enum_names = sorted({
        f.name for f in variable_op["fields"]
        if f.name and f.type in SIMPLE_SUM_NAMES and not f.seq
    })
    bool_names = sorted({
        f.name for f in variable_op["fields"]
        if f.name and f.type == "bool" and not f.seq
    })
    string_names = sorted({
        f.name for f in variable_op["fields"]
        if f.name and f.type in ("string", "identifier") and not f.seq
        and f.name not in ("name", "dependencies", "self_argument")
    })
    string_names.append("self_argument")
    string_names = sorted(set(string_names))

    for fname in enum_names:
        lines.extend([
            f'    if (strcmp(field, "{fname}") == 0) {{',
            "        const char *en = asr_pp_enum_field_name(",
            "            field, asr_get_field_i64(op, field, 0));",
            "        if (en) {",
            '            snprintf(buf, bufsz, "  %s = #asr.%s<%s>,", field,',
            "                asr_pp_enum_attr_category(field), en);",
            "            return true;",
            "        }",
            "    }",
        ])

    for fname in bool_names:
        lines.extend([
            f'    if (strcmp(field, "{fname}") == 0) {{',
            '        snprintf(buf, bufsz, "  %s = %s,", field,',
            '            asr_get_field_bool(op, field, false) ? "true" : "false");',
            "        return true;",
            "    }",
        ])

    for fname in string_names:
        lines.extend([
            f'    if (strcmp(field, "{fname}") == 0) {{',
            "        string s = asr_get_field_str(op, field);",
            '        snprintf(buf, bufsz, "  %s = \\"%.*s\\",", field,',
            "            (int)s.size, s.str ? s.str : \"\");",
            "        return true;",
            "    }",
        ])

    lines.extend([
        '    if (strcmp(field, "type_declaration") == 0) {',
        "        string sym = asr_get_field_str(op, field);",
        "        if (sym.size == 0) {",
        '            snprintf(buf, bufsz, "  %s = null,", field);',
        "        } else {",
        '            snprintf(buf, bufsz, "  %s = @%.*s,", field,',
        "                (int)sym.size, sym.str ? sym.str : \"\");",
        "        }",
        "        return true;",
        "    }",
        "    return false;",
        "}",
    ])
    return lines


def _gen_print_policy_lines(ops: list[dict]) -> list[str]:
    """Pretty-print elision and field formatters (body only, no file header)."""
    variable = next((o for o in ops if o["name"] == "Variable"), None)
    lines = [
        "typedef enum {",
        "    ASR_PP_ELIDE_NEVER = 0,",
        "    ASR_PP_ELIDE_ALWAYS,",
        "    ASR_PP_ELIDE_I64_ZERO,",
        "    ASR_PP_ELIDE_BOOL_FALSE,",
        "    ASR_PP_ELIDE_STR_EMPTY,",
        "} ASR_PpElideKind;",
        "",
        "typedef struct {",
        "    const char *field;",
        "    ASR_PpElideKind kind;",
        "} ASR_PpVariableElideRule;",
        "",
    ]
    if variable:
        lines.append("static const ASR_PpVariableElideRule ASR_PP_VARIABLE_ELIDE[] = {")
        for f in variable["fields"]:
            fname = f.name or f.type
            rule = VARIABLE_FIELD_ELIDE.get(fname)
            if not rule:
                continue
            c_kind = PP_ELIDE_C_ENUM[rule]
            lines.append(f'    {{"{fname}", {c_kind}}},')
        lines.extend([
            "};",
            "static const size_t ASR_PP_VARIABLE_ELIDE_COUNT =",
            "    sizeof(ASR_PP_VARIABLE_ELIDE) / sizeof(ASR_PP_VARIABLE_ELIDE[0]);",
            "",
        ])
    else:
        lines.extend([
            "static const ASR_PpVariableElideRule ASR_PP_VARIABLE_ELIDE[] = {};",
            "static const size_t ASR_PP_VARIABLE_ELIDE_COUNT = 0;",
            "",
        ])

    enum_fields = collect_variable_enum_pp_fields(variable)
    lines.extend([
        "typedef const char *(*ASR_PpEnumNameFn)(int64_t);",
        "",
        "typedef struct {",
        "    const char *field;",
        "    const char *attr_category;",
        "    ASR_PpEnumNameFn name_fn;",
        "} ASR_PpEnumFieldDesc;",
        "",
        "static const ASR_PpEnumFieldDesc ASR_PP_ENUM_FIELDS[] = {",
    ])
    for fname, asdl_type in enum_fields:
        fn = f"asr_enum_{snake_case(asdl_type)}_name"
        cat = enum_pp_attr_category(asdl_type)
        lines.append(f'    {{"{fname}", "{cat}", {fn}}},')
    lines.extend([
        "};",
        "static const size_t ASR_PP_ENUM_FIELDS_COUNT =",
        "    sizeof(ASR_PP_ENUM_FIELDS) / sizeof(ASR_PP_ENUM_FIELDS[0]);",
        "",
        "static inline const ASR_PpEnumFieldDesc *asr_pp_lookup_enum_field(",
        "        const char *field) {",
        "    if (!field) {",
        "        return NULL;",
        "    }",
        "    for (size_t i = 0; i < ASR_PP_ENUM_FIELDS_COUNT; ++i) {",
        "        if (strcmp(field, ASR_PP_ENUM_FIELDS[i].field) == 0) {",
        "            return &ASR_PP_ENUM_FIELDS[i];",
        "        }",
        "    }",
        "    return NULL;",
        "}",
        "",
        "static inline bool asr_pp_apply_elide_rule(",
        "        ASR_PpElideKind kind, MLIR_OpHandle op, const char *field) {",
        "    switch (kind) {",
        "    case ASR_PP_ELIDE_ALWAYS:",
        "        return true;",
        "    case ASR_PP_ELIDE_I64_ZERO:",
        "        return asr_get_field_i64(op, field, 0) == 0;",
        "    case ASR_PP_ELIDE_BOOL_FALSE:",
        "        return !asr_get_field_bool(op, field, false);",
        "    case ASR_PP_ELIDE_STR_EMPTY:",
        "        return asr_get_field_str(op, field).size == 0;",
        "    default:",
        "        return false;",
        "    }",
        "}",
        "",
        "static inline bool asr_pp_variable_field_is_default(",
        "        const char *field, MLIR_OpHandle op) {",
        "    for (size_t i = 0; i < ASR_PP_VARIABLE_ELIDE_COUNT; ++i) {",
        "        if (strcmp(field, ASR_PP_VARIABLE_ELIDE[i].field) == 0) {",
        "            return asr_pp_apply_elide_rule(",
        "                ASR_PP_VARIABLE_ELIDE[i].kind, op, field);",
        "        }",
        "    }",
        "    return false;",
        "}",
        "",
        "static inline const char *asr_pp_enum_field_name(",
        "        const char *field, int64_t v) {",
        "    const ASR_PpEnumFieldDesc *desc = asr_pp_lookup_enum_field(field);",
        "    if (!desc || !desc->name_fn) {",
        "        return NULL;",
        "    }",
        "    return desc->name_fn(v);",
        "}",
        "",
        "static inline const char *asr_pp_enum_attr_category(const char *field) {",
        "    const ASR_PpEnumFieldDesc *desc = asr_pp_lookup_enum_field(field);",
        "    if (desc && desc->attr_category) {",
        "        return desc->attr_category;",
        "    }",
        "    return field;",
        "}",
    ])
    lines.extend(gen_variable_scalar_field_printer(variable))
    return lines


def gen_print_helpers_h(enums: dict[str, list[str]], ops: list[dict]) -> str:
    """Enum name tables + pretty-print elision/format helpers for the ASR dump."""
    lines = generated_file_lines(
        "#pragma once",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "#include \"asr_dialect_storage.h\"",
        "",
        "#include <string.h>",
        "",
    )
    lines.extend(_gen_enum_print_lines(enums))
    lines.extend(_gen_print_policy_lines(ops))
    return "\n".join(lines) + "\n"


def write_outputs(
    ops: list[dict],
    enums: dict[str, list[str]],
    out_mlir_dir: Path,
    out_codegen_dir: Path,
    policy_path: Path,
) -> None:
    out_mlir_dir.mkdir(parents=True, exist_ok=True)
    overrides = parse_storage_policy_overrides(policy_path)
    region_layout = parse_region_layout(policy_path)
    all_policies = compute_op_storage_policies(ops, overrides, region_layout)
    validate_policy_coverage(ops, overrides, all_policies)

    outputs = {
        out_mlir_dir / "asr_dialect_schema.h": gen_schema_h(ops, all_policies),
        out_mlir_dir / "asr_dialect_api_generated.h": gen_api_generated_h(
            ops, all_policies),
        out_mlir_dir / "asr_dialect_lowering_dispatch.h": gen_lowering_dispatch_h(ops),
        out_mlir_dir / "asr_dialect_print_helpers.h": gen_print_helpers_h(
            enums, ops),
        out_mlir_dir / "asr_dialect_storage_merged.h": gen_storage_merged_h(
            ops, all_policies),
        out_mlir_dir / "asr_dialect_layout_fields.h": gen_dialect_layout_h(),
    }
    for path, content in outputs.items():
        path.write_text(content, encoding="utf-8")
        print(f"Wrote {path} ({len(content)} bytes)")
    update_visitor_sources(out_codegen_dir, ops)


def check_outputs(
    ops: list[dict],
    enums: dict[str, list[str]],
    out_mlir_dir: Path,
    out_codegen_dir: Path,
    policy_path: Path,
) -> bool:
    overrides = parse_storage_policy_overrides(policy_path)
    region_layout = parse_region_layout(policy_path)
    all_policies = compute_op_storage_policies(ops, overrides, region_layout)
    validate_policy_coverage(ops, overrides, all_policies)
    expected = {
        out_mlir_dir / "asr_dialect_schema.h": gen_schema_h(ops, all_policies),
        out_mlir_dir / "asr_dialect_api_generated.h": gen_api_generated_h(
            ops, all_policies),
        out_mlir_dir / "asr_dialect_lowering_dispatch.h": gen_lowering_dispatch_h(ops),
        out_mlir_dir / "asr_dialect_print_helpers.h": gen_print_helpers_h(
            enums, ops),
        out_mlir_dir / "asr_dialect_storage_merged.h": gen_storage_merged_h(
            ops, all_policies),
        out_mlir_dir / "asr_dialect_layout_fields.h": gen_dialect_layout_h(),
    }
    ok = True
    for path, content in expected.items():
        if not path.exists():
            print(f"MISSING: {path}", file=sys.stderr)
            ok = False
            continue
        existing = path.read_text(encoding="utf-8")
        if existing != content:
            print(f"STALE: {path}", file=sys.stderr)
            ok = False
    ok = check_visitor_sources(out_codegen_dir, ops) and ok
    return ok


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--asdl", type=Path, required=True)
    parser.add_argument("--out-mlir-dir", type=Path, required=True)
    parser.add_argument("--out-codegen-dir", type=Path, required=True,
                        help="libasr/codegen directory for visitor .h/.cpp")
    parser.add_argument("--policy", type=Path, default=None,
                        help="Path to asr_dialect_storage_policy.h")
    parser.add_argument("--check", action="store_true",
                        help="Verify committed generated files match ASR.asdl")
    args = parser.parse_args()

    policy_path = args.policy
    if policy_path is None:
        policy_path = args.out_mlir_dir.parent / "lfortran" / "asr_dialect_storage_policy.h"

    mod = asdl.parse(str(args.asdl))
    ops = collect_ops(mod)
    enums = collect_simple_enums(mod)
    print(f"Generated {len(ops)} dialect ops")

    if args.check:
        return 0 if check_outputs(ops, enums, args.out_mlir_dir,
                                   args.out_codegen_dir, policy_path) else 1

    write_outputs(ops, enums, args.out_mlir_dir, args.out_codegen_dir, policy_path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
