#!/usr/bin/env python3
"""
Generate ASR MLIR dialect artifacts from ASR.asdl (Design A: 1 constructor -> 1 asr.* op).

Outputs:
  - asr_dialect_schema.h
  - asr_dialect_api_generated.h
  - asr_dialect_lowering_dispatch.h
  - asr_dialect_enum_print.h
  - asr_dialect_print_policy.h
  - asr_to_asr_dialect.h (generated declarations section)
  - asr_to_asr_dialect.cpp (generated implementations section)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import asdl

# ASDL types that are simple enum sums (not dialect ops).
# They appear as fields for other operations. 
SIMPLE_SUM_NAMES = {
    "cast_kind", "storage_type", "access", "intent", "deftype", "presence",
    "pass_attr", "abi", "codimension_type", "enumtype", "array_physical_type",
    "string_physical_type", "string_length_kind", "binop", "reduction_op",
    "logicalbinop", "cmpop", "integerboz", "arraybound", "arraystorage",
    "string_format_kind", "omp_region_type", "map_type", "schedule_type",
}

# Categories that produce dialect ops (top-level sum names in ASR.asdl).
OP_CATEGORIES = {"unit", "symbol", "stmt", "expr", "ttype"}

# Product-type sums that also become ops (records used as node payloads).
PRODUCT_OP_CATEGORIES = {
    "dimension", "codimension", "alloc_arg", "attribute", "attribute_arg",
    "call_arg", "reduction_expr", "tbind", "array_index", "do_loop_head",
    "case_stmt", "type_stmt", "rank_stmt", "require_instantiation", "omp_clause",
}

# Ops with ASR-dialect -> high-level MLIR lowering handlers (compile path).
COMPILE_SUPPORTED_OPS = {
    # Arithmetic
    "IntegerConstant", "IntegerBinOp", "IntegerCompare", "IntegerUnaryMinus",
    "IntegerBitNot", "RealConstant", "RealBinOp", "RealCompare", "RealUnaryMinus",
    "Cast", "Var", "LogicalConstant", "LogicalNot", "LogicalCompare", "LogicalBinOp",
    "StringFormat",
    # Array
    "ArrayItem", "ArrayConstant", "ArrayConstructor", "ArraySize", "ArrayBound",
    "ArraySection", "ArrayTranspose", "ArrayReshape", "ArrayPhysicalCast",
    # Intrinsics
    "IntrinsicElementalFunction", "IntrinsicArrayFunction", "IntrinsicImpureFunction",
    "IntrinsicImpureSubroutine",
    # Scaffolding
    "TranslationUnit", "Program", "Function", "Variable", "Assignment",
    "Return", "Print", "FileWrite", "DoLoop", "If", "ErrorStop", "Allocate",
    # Types
    "Integer", "Real", "Logical", "Complex", "Array",
}

# Back-compat alias (prefer COMPILE_SUPPORTED_OPS in new code).
LOWERED_OPS = COMPILE_SUPPORTED_OPS

# Fields omitted from dialect op storage (handled by emitter policy).
# symbol_table is materialized as asr.symtab/asr.body regions in the visitor.
SKIP_FIELDS = {"location"}

# Compact pretty-print elision for asr.symbol.variable (field name -> rule tag).
VARIABLE_FIELD_ELIDE = {
    "name": "always",
    "intent": "i64_zero",
    "storage": "i64_zero",
    "abi": "i64_zero",
    "access": "i64_zero",
    "presence": "i64_zero",
    "pass_attr": "i64_zero",
    "value_attr": "bool_false",
    "target_attr": "bool_false",
    "contiguous_attr": "bool_false",
    "is_volatile": "bool_false",
    "is_protected": "bool_false",
    "bindc_name": "str_empty",
    "self_argument": "str_empty",
}

PP_ELIDE_C_ENUM = {
    "always": "ASR_PP_ELIDE_ALWAYS",
    "i64_zero": "ASR_PP_ELIDE_I64_ZERO",
    "bool_false": "ASR_PP_ELIDE_BOOL_FALSE",
    "str_empty": "ASR_PP_ELIDE_STR_EMPTY",
}


def enum_pp_attr_category(asdl_type: str) -> str:
    """MLIR attribute dialect prefix for #asr.<category><kw>."""
    if asdl_type == "storage_type":
        return "storage"
    return snake_case(asdl_type)


CPP_KEYWORDS = {
    "inline", "static", "class", "virtual", "public", "private", "protected",
    "template", "operator", "new", "delete", "this", "friend", "register",
    "default",
    # unistd.h macros on Linux — must not be used as C++ identifiers
    "read", "write", "open", "close",
}

GENERATED_FILE_BANNER = "// Generated by asdl_to_asr_dialect.py — do not edit."


def generated_file_lines(*lines: str) -> list[str]:
    """Prefix fully generated file contents with the standard banner."""
    return [GENERATED_FILE_BANNER, ""] + list(lines)


def snake_case(name: str) -> str:
    out = []
    for i, ch in enumerate(name):
        if ch.isupper() and i > 0:
            out.append("_")
        out.append(ch.lower())
    return "".join(out)


def enum_kind(category: str, name: str) -> str:
    return f"ASR_DIALECT_OP_{category.upper()}_{name.upper()}"


def mlir_op_name(name: str) -> str:
    return f"asr.{snake_case(name)}"

def c_param_name(name: str) -> str:
    if name in CPP_KEYWORDS:
        return name + "_"
    return name

# Map ASDL field types to MLIR field kinds, in C++ Codes.
def field_kind(asdl_type: str, seq: bool, opt: bool) -> str:
    if asdl_type in SIMPLE_SUM_NAMES:
        base = "I64"
    elif asdl_type == "symbol":
        base = "SYMBOL_REF"
    elif asdl_type in ("expr", "stmt", "ttype", "node"):
        base = asdl_type.upper()
    elif asdl_type == "identifier":
        base = "IDENTIFIER"
    elif asdl_type == "string":
        base = "STRING"
    elif asdl_type == "int":
        base = "I64"
    elif asdl_type == "bool":
        base = "BOOL"
    elif asdl_type == "float":
        base = "F64"
    elif asdl_type == "void":
        base = "VOID"
    elif asdl_type.endswith("Type"):
        base = "I64"
    else:
        base = "OP"
    if seq:
        return f"ASR_FIELD_{base}_SEQ"
    if opt:
        return f"ASR_FIELD_{base}_OPT"
    return f"ASR_FIELD_{base}"

OP_HANDLE_SEQ_FIELD_KINDS = {
    "ASR_FIELD_OP_SEQ",
    "ASR_FIELD_NODE_SEQ",
    "ASR_FIELD_EXPR_SEQ",
    "ASR_FIELD_STMT_SEQ",
    "ASR_FIELD_SYMBOL_SEQ",
}


# Assign a ASR Value inside a Node to ASR Dialect Field structure.
def gen_field_assign(i: int, f: asdl.Field, param: str) -> list[str]:
    fname = f.name or f.type
    fk = field_kind(f.type, f.seq, f.opt)
    lines = [
        f"    fields[{i}].kind = {fk};",
        f"    fields[{i}].name = \"{fname}\";",
    ]
    if f.type in ("identifier", "string", "symbol"):
        lines.append(f"    fields[{i}].value.str = {param};")
    elif f.type == "bool":
        lines.append(f"    fields[{i}].value.b = {param};")
    elif f.type == "float":
        lines.append(f"    fields[{i}].value.f64 = {param};")
    elif f.type == "int" or is_enum_field(f.type) or f.type == "void":
        lines.append(f"    fields[{i}].value.i64 = {param};")
    elif f.type == "ttype":
        lines.append(f"    fields[{i}].value.type = {param};")
    elif f.seq and fk in OP_HANDLE_SEQ_FIELD_KINDS:
        lines.append(f"    fields[{i}].value.op_seq.items = {param};")
        lines.append(f"    fields[{i}].value.op_seq.n_items = n_{param};")
    else:
        lines.append(f"    fields[{i}].value.op = {param};")
    return lines


# Create a list of operations from the ASDL module.
def stored_dialect_fields(op: dict) -> list:
    """Fields stored on ASR dialect ops (may differ from ASR.asdl for mlir-new)."""
    if op["name"] == "ArrayConstant":
        # Do not store raw ASR heap pointers in dialect IR; use element expr ops.
        return [
            asdl.Field("expr", "elements", seq=True),
            asdl.Field("ttype", "type"),
            asdl.Field("arraystorage", "storage_format"),
        ]
    return [f for f in op["fields"] if f.name not in SKIP_FIELDS]


def collect_ops(mod: asdl.Module) -> list[dict]:
    ops = []
    # Ignore simple no-operation enum types, like intent.
    for dfn in mod.dfns:
        cat = dfn.name
        val = dfn.value
        if isinstance(val, asdl.Product):
            ops.append({
                "category": cat,
                "name": cat,
                "fields": val.fields,
                "kind": enum_kind(cat, cat),
                "mlir_name": mlir_op_name(cat),
            })
        elif cat in OP_CATEGORIES or cat in PRODUCT_OP_CATEGORIES:
            for cons in val.types:
                ops.append({
                    "category": cat,
                    "name": cons.name,
                    "fields": cons.fields,
                    "kind": enum_kind(cat, cons.name),
                    "mlir_name": mlir_op_name(cons.name),
                })
    ops.sort(key=lambda o: (o["category"], o["name"]))
    return ops


def collect_simple_enums(mod: asdl.Module) -> dict[str, list[str]]:
    enums = {}
    for dfn in mod.dfns:
        # Collect simple enum types, like binop, intent etc, which dont have
        # an ASR Dialect operation (example: intent).
        if dfn.name in SIMPLE_SUM_NAMES and isinstance(dfn.value, asdl.Sum):
            enums[dfn.name] = [c.name for c in dfn.value.types]
    return enums


def gen_schema_h(ops: list[dict]) -> str:
    cat_map = {
        "unit": "ASR_DIALECT_CATEGORY_UNIT",
        "symbol": "ASR_DIALECT_CATEGORY_SYMBOL",
        "stmt": "ASR_DIALECT_CATEGORY_STMT",
        "expr": "ASR_DIALECT_CATEGORY_EXPR",
        "ttype": "ASR_DIALECT_CATEGORY_TTYPE",
    }
    lines = generated_file_lines(
        "#pragma once",
        "",
        "#include <stddef.h>",
        "",
        "typedef enum {",
        "    ASR_DIALECT_OP_INVALID = 0,",
    )
    for op in ops:
        lines.append(f"    {op['kind']},")
    lines.extend([
        "    ASR_DIALECT_OP_COUNT",
        "} ASR_DialectOpKind;",
        "",
        "typedef enum {",
        "    ASR_DIALECT_CATEGORY_UNIT,",
        "    ASR_DIALECT_CATEGORY_SYMBOL,",
        "    ASR_DIALECT_CATEGORY_STMT,",
        "    ASR_DIALECT_CATEGORY_EXPR,",
        "    ASR_DIALECT_CATEGORY_TTYPE,",
        "    ASR_DIALECT_CATEGORY_PRODUCT,",
        "} ASR_DialectCategory;",
        "",
        "typedef enum {",
        "    ASR_FIELD_I64, ASR_FIELD_F64, ASR_FIELD_BOOL,",
        "    ASR_FIELD_STRING, ASR_FIELD_IDENTIFIER,",
        "    ASR_FIELD_SYMBOL_REF, ASR_FIELD_SYMBOL_REF_OPT, ASR_FIELD_SYMBOL_REF_SEQ,",
        "    ASR_FIELD_EXPR, ASR_FIELD_STMT, ASR_FIELD_SYMBOL,",
        "    ASR_FIELD_TTYPE, ASR_FIELD_NODE, ASR_FIELD_OP,",
        "    ASR_FIELD_VOID, ASR_FIELD_I64_SEQ, ASR_FIELD_F64_SEQ,",
        "    ASR_FIELD_BOOL_SEQ, ASR_FIELD_STRING_SEQ,",
        "    ASR_FIELD_IDENTIFIER_SEQ, ASR_FIELD_EXPR_SEQ,",
        "    ASR_FIELD_STMT_SEQ, ASR_FIELD_SYMBOL_SEQ,",
        "    ASR_FIELD_TTYPE_SEQ, ASR_FIELD_NODE_SEQ, ASR_FIELD_OP_SEQ,",
        "    ASR_FIELD_EXPR_OPT, ASR_FIELD_STMT_OPT, ASR_FIELD_SYMBOL_OPT,",
        "    ASR_FIELD_TTYPE_OPT, ASR_FIELD_NODE_OPT, ASR_FIELD_I64_OPT,",
        "    ASR_FIELD_F64_OPT, ASR_FIELD_STRING_OPT,",
        "    ASR_FIELD_IDENTIFIER_OPT, ASR_FIELD_BOOL_OPT,",
        "} ASR_DialectFieldKind;",
        "",
        "typedef enum { ASR_FIELD_REQUIRED, ASR_FIELD_OPTIONAL } ASR_FieldPresence;",
        "",
        "typedef struct {",
        "    const char *name;",
        "    ASR_DialectFieldKind kind;",
        "    ASR_FieldPresence presence;",
        "} ASR_DialectFieldDesc;",
        "",
        "typedef struct {",
        "    ASR_DialectOpKind kind;",
        "    ASR_DialectCategory category;",
        "    const char *asr_name;",
        "    const char *mlir_name;",
        "    size_t n_fields;",
        "    const ASR_DialectFieldDesc *fields;",
        "} ASR_DialectOpSchema;",
        "",
    ])
    for op in ops:
        stored = stored_dialect_fields(op)
        if not stored:
            continue
        lines.append(f"static const ASR_DialectFieldDesc {op['kind']}_FIELDS[] = {{")
        for f in stored:
            fk = field_kind(f.type, f.seq, f.opt)
            pres = "ASR_FIELD_OPTIONAL" if f.opt else "ASR_FIELD_REQUIRED"
            fname = f.name or f.type
            lines.append(f'    {{"{fname}", {fk}, {pres}}},')
        lines.append("};")
        lines.append("")

    lines.append("static const ASR_DialectOpSchema ASR_DIALECT_SCHEMA[] = {")
    for op in ops:
        stored = stored_dialect_fields(op)
        cat = cat_map.get(op["category"], "ASR_DIALECT_CATEGORY_PRODUCT")
        fields_ref = f"{op['kind']}_FIELDS" if stored else "NULL"
        lines.append("    {")
        lines.append(f"        .kind = {op['kind']},")
        lines.append(f"        .category = {cat},")
        lines.append(f'        .asr_name = "{op["name"]}",')
        lines.append(f'        .mlir_name = "{op["mlir_name"]}",')
        lines.append(f"        .n_fields = {len(stored)},")
        lines.append(f"        .fields = {fields_ref},")
        lines.append("    },")
    lines.extend([
        "};",
        "",
        "static const size_t ASR_DIALECT_SCHEMA_COUNT =",
        "    sizeof(ASR_DIALECT_SCHEMA) / sizeof(ASR_DIALECT_SCHEMA[0]);",
        "",
    ])
    return "\n".join(lines)


def gen_api_generated_h(ops: list[dict]) -> str:
    lines = generated_file_lines(
        "// Include from C/C++ translation units only (not from asr_dialect_api.h).",
        "#pragma once",
        "",
        "#include \"asr_dialect_api.h\"",
        "",
    )
    for op in ops:
        stored = stored_dialect_fields(op)
        params = ["MLIR_Context *ctx", "MLIR_LocationHandle loc"]
        for f in stored:
            fname = c_param_name(f.name or f.type)
            if f.seq and f.type in ("expr", "stmt", "node"):
                params.append(f"MLIR_OpHandle *{fname}")
                params.append(f"size_t n_{fname}")
            elif f.type in ("expr", "stmt", "node"):
                params.append(f"MLIR_OpHandle {fname}")
            elif f.type == "symbol":
                params.append(f"ASR_SymbolRef {fname}")
            elif f.type == "ttype":
                params.append(f"MLIR_TypeHandle {fname}")
            elif f.type in ("identifier", "string"):
                params.append(f"string {fname}")
            elif f.type == "int" or is_enum_field(f.type):
                params.append(f"int64_t {fname}")
            elif f.type == "bool":
                params.append(f"bool {fname}")
            elif f.type == "float":
                params.append(f"double {fname}")
            elif f.seq:
                params.append(f"MLIR_OpHandle *{fname}")
                params.append(f"size_t n_{fname}")
            else:
                params.append(f"MLIR_OpHandle {fname}")
        fn = f"ASR_Create{op['name']}Op"
        lines.append(f"static inline MLIR_OpHandle {fn}(")
        lines.append("        " + ",\n        ".join(params) + ") {")
        n = len(stored)
        if n == 0:
            lines.append("    (void)ctx; (void)loc;")
            lines.append(f"    return ASR_DialectCreateOp(ctx, {op['kind']}, loc, NULL, 0);")
        else:
            lines.append(f"    ASR_DialectField fields[{n}];")
            for i, f in enumerate(stored):
                param = c_param_name(f.name or f.type)
                lines.extend(gen_field_assign(i, f, param))
            lines.append(f"    return ASR_DialectCreateOp(ctx, {op['kind']}, loc, fields, {n});")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def asr_member(field: asdl.Field) -> str:
    if field.name:
        return f"m_{field.name}"
    return field.type


def asr_count_member(field: asdl.Field) -> str:
    assert field.name
    return f"n_{field.name}"


def is_enum_field(asdl_type: str) -> bool:
    return asdl_type in SIMPLE_SUM_NAMES or asdl_type.endswith("Type")


def cpp_emit_field(field: asdl.Field) -> str:
    name = field.name
    asdl_type = field.type
    if name in SKIP_FIELDS:
        return ""
    fname = c_param_name(name or asdl_type)
    member = asr_member(field)
    if asdl_type == "expr":
        if field.seq:
            count = asr_count_member(field)
            return (f"        size_t n_{fname} = x.{count};\n"
                    f"        MLIR_OpHandle *{fname} = emit_expr_op_array(x.{member}, n_{fname});")
        if field.opt:
            return (f"        MLIR_ValueHandle {fname} = MLIR_INVALID_HANDLE;\n"
                    f"        if (x.{member}) {{ {fname} = emit_expr(*x.{member}); }}")
        return f"        MLIR_ValueHandle {fname} = emit_expr(*x.{member});"
    if asdl_type == "stmt":
        if field.seq:
            count = asr_count_member(field)
            return (f"        size_t n_{fname} = x.{count};\n"
                    f"        MLIR_OpHandle *{fname} = emit_stmt_op_array(x.{member}, n_{fname});")
        if field.opt:
            return (f"        MLIR_ValueHandle {fname} = MLIR_INVALID_HANDLE;\n"
                    f"        if (x.{member}) {{ {fname} = emit_stmt(*x.{member}); }}")
        return f"        MLIR_ValueHandle {fname} = emit_stmt(*x.{member});"
    if asdl_type == "symbol":
        if field.seq:
            return f"        string {fname} = emit_symbol_seq_ref(x.{member}, x.{asr_count_member(field)});"
        if field.opt:
            return (f"        string {fname} = str_lit(\"\");\n"
                    f"        if (x.{member}) {{ {fname} = emit_symbol_ref(*x.{member}); }}")
        return f"        string {fname} = emit_symbol_ref(*x.{member});"
    if asdl_type == "ttype":
        if field.seq:
            return f"        MLIR_TypeHandle {fname} = emit_type_seq_value(x.{member}, x.{asr_count_member(field)});"
        if field.opt:
            return (f"        MLIR_TypeHandle {fname} = MLIR_INVALID_HANDLE;\n"
                    f"        if (x.{member}) {{ {fname} = convert_type(*x.{member}); }}")
        return f"        MLIR_TypeHandle {fname} = convert_type(*x.{member});"
    if asdl_type == "identifier":
        if field.seq:
            return (f"        string {fname} = emit_identifier_seq("
                    f"x.{member}, x.{asr_count_member(field)});")
        return f"        string {fname} = asr_cstr(x.{member});"
    if asdl_type == "string":
        if field.opt:
            return (f"        string {fname} = str_lit(\"\");\n"
                    f"        if (x.{member}) {{ {fname} = asr_cstr(x.{member}); }}")
        return f"        string {fname} = asr_cstr(x.{member});"
    if asdl_type == "int":
        return f"        int64_t {fname} = x.{member};"
    if asdl_type == "bool":
        return f"        bool {fname} = x.{member};"
    if asdl_type == "float":
        return f"        double {fname} = x.{member};"
    if asdl_type == "void":
        return f"        int64_t {fname} = (int64_t)x.{member};"
    if is_enum_field(asdl_type):
        return f"        int64_t {fname} = (int64_t)x.{member};"
    if asdl_type == "array_index" and field.seq:
        count = asr_count_member(field)
        return (f"        size_t n_{fname} = x.{count};\n"
                f"        MLIR_OpHandle *{fname} = emit_array_index_op_array(x.{member}, n_{fname});")
    if field.seq and field_kind(asdl_type, True, field.opt) == "ASR_FIELD_OP_SEQ":
        count = asr_count_member(field)
        return (f"        size_t n_{fname} = x.{count};\n"
                f"        MLIR_OpHandle *{fname} = emit_product_op_array(x.{member}, n_{fname});")
    if field.seq:
        count = asr_count_member(field)
        return (f"        size_t n_{fname} = x.{count};\n"
                f"        MLIR_ValueHandle {fname} = MLIR_INVALID_HANDLE;\n"
                f"        (void)x.{member};")
    emit_fn = PRODUCT_EMIT_CPP.get(asdl_type)
    if emit_fn:
        if field.opt:
            return (f"        MLIR_ValueHandle {fname} = MLIR_INVALID_HANDLE;\n"
                    f"        if (x.{member}) {{ {fname} = {emit_fn}(*x.{member}); }}")
        return f"        MLIR_ValueHandle {fname} = {emit_fn}(x.{member});"
    if field.opt:
        return (f"        MLIR_ValueHandle {fname} = MLIR_INVALID_HANDLE;\n"
                f"        if (x.{member}) {{ {fname} = emit_product_value(x.{member}); }}")
    return f"        MLIR_ValueHandle {fname} = emit_product_value(x.{member});"


# Hand-written in asr_to_asr_dialect.cpp (module layout + multi-stmt do bodies).
VISITOR_DECL_START = "// >>> GENERATED VISITOR DECLARATIONS >>>"
VISITOR_DECL_END = "// <<< END GENERATED VISITOR DECLARATIONS <<<"
VISITOR_IMPL_START = "// >>> GENERATED VISITOR IMPLEMENTATIONS >>>"
VISITOR_IMPL_END = "// <<< END GENERATED VISITOR IMPLEMENTATIONS <<<"

SKIP_VISITOR_OPS = {
    "Program", "TranslationUnit", "DoLoop", "Print", "FileWrite", "Variable",
    "StringFormat", "ArrayConstructor", "ArrayItem", "ArrayConstant",
}

# Embedded ASR products emitted by helpers in asr_to_asr_dialect.cpp.
PRODUCT_EMIT_CPP = {
    "do_loop_head": "emit_do_loop_head",
    "array_index": "emit_array_index",
}


def visitor_create_args(fields: list[asdl.Field]) -> list[str]:
    """Build ASR_Create*Op argument list matching generated API signatures."""
    args = []
    for f in fields:
        fname = c_param_name(f.name or f.type)
        fk = field_kind(f.type, f.seq, f.opt)
        # Product/node sequences use MLIR_OpHandle* + count in generated API.
        if f.seq and fk in (
            "ASR_FIELD_OP_SEQ",
            "ASR_FIELD_NODE_SEQ",
            "ASR_FIELD_EXPR_SEQ",
            "ASR_FIELD_STMT_SEQ",
        ):
            args.append(fname)
            args.append(f"n_{fname}")
            continue
        args.append(fname)
    return args


def gen_visitor_declarations(ops: list[dict]) -> str:
    lines = generated_file_lines()
    for op in ops:
        if op["category"] not in ("expr", "stmt"):
            continue
        if op["name"] in SKIP_VISITOR_OPS:
            continue
        lines.append(
            f"    void visit_{op['name']}(const ASR::{op['name']}_t &x);")
    if len(lines) == 2:
        lines.append("")
    return "\n".join(lines) + "\n"


def gen_visitor_implementations(ops: list[dict]) -> str:
    lines = generated_file_lines()
    for op in ops:
        if op["category"] not in ("expr", "stmt"):
            continue
        if op["name"] in SKIP_VISITOR_OPS:
            continue
        stored = [f for f in op["fields"] if f.name not in SKIP_FIELDS]
        lines.append(f"void ASRToAsrDialectVisitor::visit_{op['name']}(const ASR::{op['name']}_t &x) {{")
        for f in stored:
            code = cpp_emit_field(f)
            if code:
                # Drop class-body indent from helper snippets.
                lines.append(code[4:] if code.startswith("        ") else code)
        lines.append("    MLIR_LocationHandle op_loc = loc(x.base.base.loc);")
        fn = f"ASR_Create{op['name']}Op"
        create_args = visitor_create_args(stored)
        if stored:
            lines.append(
                f"    last_value = {fn}(&ctx, op_loc, {', '.join(create_args)});")
        else:
            lines.append(f"    last_value = {fn}(&ctx, op_loc);")
        if op["category"] == "stmt":
            lines.append("    append_current_stmt(last_value);")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def replace_marked_section(path: Path, start: str, end: str, content: str) -> None:
    text = path.read_text(encoding="utf-8")
    start_idx = text.find(start)
    end_idx = text.find(end)
    if start_idx < 0 or end_idx < 0 or end_idx < start_idx:
        raise RuntimeError(f"marker pair not found in {path}")
    end_idx += len(end)
    new_text = text[:start_idx] + start + "\n" + content + end + text[end_idx:]
    path.write_text(new_text, encoding="utf-8")


def check_marked_section(path: Path, start: str, end: str, expected: str) -> bool:
    if not path.exists():
        print(f"MISSING: {path}", file=sys.stderr)
        return False
    text = path.read_text(encoding="utf-8")
    start_idx = text.find(start)
    end_idx = text.find(end)
    if start_idx < 0 or end_idx < 0 or end_idx < start_idx:
        print(f"MARKERS MISSING: {path}", file=sys.stderr)
        return False
    start_idx += len(start)
    existing = text[start_idx:end_idx]
    if existing != "\n" + expected:
        print(f"STALE: {path} ({start})", file=sys.stderr)
        return False
    return True


def update_visitor_sources(codegen_dir: Path, ops: list[dict]) -> None:
    decls = gen_visitor_declarations(ops)
    impls = gen_visitor_implementations(ops)
    replace_marked_section(
        codegen_dir / "asr_to_asr_dialect.h",
        VISITOR_DECL_START, VISITOR_DECL_END, decls)
    replace_marked_section(
        codegen_dir / "asr_to_asr_dialect.cpp",
        VISITOR_IMPL_START, VISITOR_IMPL_END, impls)
    print(f"Updated {codegen_dir / 'asr_to_asr_dialect.h'}")
    print(f"Updated {codegen_dir / 'asr_to_asr_dialect.cpp'}")


def check_visitor_sources(codegen_dir: Path, ops: list[dict]) -> bool:
    decls = gen_visitor_declarations(ops)
    impls = gen_visitor_implementations(ops)
    ok = check_marked_section(
        codegen_dir / "asr_to_asr_dialect.h",
        VISITOR_DECL_START, VISITOR_DECL_END, decls)
    ok = check_marked_section(
        codegen_dir / "asr_to_asr_dialect.cpp",
        VISITOR_IMPL_START, VISITOR_IMPL_END, impls) and ok
    return ok


def gen_lowering_dispatch_h(ops: list[dict]) -> str:
    lines = generated_file_lines(
        "#pragma once",
        "",
        "#include \"asr_dialect_api.h\"",
        "",
        "/* Lowering handlers exist only for COMPILE_SUPPORTED_OPS (see asdl_to_asr_dialect.py). */",
        "",
    )
    for op in ops:
        if op["name"] in COMPILE_SUPPORTED_OPS:
            handler = f"ASR_Lower{op['name']}"
            lines.append(
                f"extern bool {handler}(ASR_LoweringContext *lc, MLIR_OpHandle op);")
    lines.extend([
        "",
        "static inline bool ASR_DialectLowerOneOp(",
        "        ASR_LoweringContext *ctx, MLIR_OpHandle op) {",
        "    ASR_DialectOpKind kind = ASR_DialectGetOpKind(op);",
        "    switch (kind) {",
    ])
    for op in ops:
        if op["name"] in COMPILE_SUPPORTED_OPS:
            handler = f"ASR_Lower{op['name']}"
            lines.append(f"    case {op['kind']}:")
            lines.append(f"        return {handler}(ctx, op);")
    lines.extend([
        "    default:",
        '        return ASR_LowerUnsupported(ctx, op, "ASR dialect op has no lowering yet");',
        "    }",
        "}",
        "",
    ])
    return "\n".join(lines)


def gen_enum_print_h(enums: dict[str, list[str]]) -> str:
    """C helpers: map semantic enum integers to keyword names for hybrid dump."""
    lines = generated_file_lines(
        "#pragma once",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "static inline const char *asr_enum_name_or_unknown(",
        "        const char *const *names, size_t n_names, int64_t v) {",
        "    if (v >= 0 && (size_t)v < n_names) {",
        "        return names[(size_t)v];",
        "    }",
        "    return NULL;",
        "}",
        "",
    )
    for enum_name, variants in sorted(enums.items()):
        c_names = f"ASR_ENUM_{enum_name.upper()}_NAMES"
        kw = [snake_case(v) for v in variants]
        lines.append(f"static const char *const {c_names}[] = {{")
        for k in kw:
            lines.append(f'    "{k}",')
        lines.append("};")
        lines.append(f"static const size_t {c_names}_COUNT = {len(kw)};")
        lines.append("")
        fn = f"asr_enum_{snake_case(enum_name)}_name"
        lines.append(f"static inline const char *{fn}(int64_t v) {{")
        lines.append(
            f"    return asr_enum_name_or_unknown({c_names}, {c_names}_COUNT, v);")
        lines.append("}")
        lines.append("")
    return "\n".join(lines) + "\n"


def collect_variable_enum_pp_fields(variable_op: dict | None) -> list[tuple[str, str]]:
    """(field name, ASDL enum type) for Variable I64 fields backed by simple sums."""
    if not variable_op:
        return []
    out: list[tuple[str, str]] = []
    for f in variable_op["fields"]:
        if not f.name or f.name in SKIP_FIELDS:
            continue
        if f.seq:
            continue
        if f.type in SIMPLE_SUM_NAMES:
            out.append((f.name, f.type))
    return sorted(out)


def gen_print_policy_h(ops: list[dict]) -> str:
    """Pretty-print elision and field-to-enum metadata for the hybrid ASR dump."""
    variable = next((o for o in ops if o["name"] == "Variable"), None)
    lines = generated_file_lines(
        "#pragma once",
        "",
        "#include \"generated/asr_dialect_schema.h\"",
        "#include \"generated/asr_dialect_enum_print.h\"",
        "#include \"asr_dialect_storage.h\"",
        "",
        "#include <string.h>",
        "",
        "typedef enum {",
        "    ASR_PP_ELIDE_NEVER = 0,",
        "    ASR_PP_ELIDE_ALWAYS,",
        "    ASR_PP_ELIDE_I64_ZERO,",
        "    ASR_PP_ELIDE_BOOL_FALSE,",
        "    ASR_PP_ELIDE_STR_EMPTY,",
        "} ASR_PpElideKind;",
        "",
        "typedef struct {",
        "    const char *field;",
        "    ASR_PpElideKind kind;",
        "} ASR_PpVariableElideRule;",
        "",
    )
    if variable:
        lines.append("static const ASR_PpVariableElideRule ASR_PP_VARIABLE_ELIDE[] = {")
        for f in variable["fields"]:
            fname = f.name or f.type
            rule = VARIABLE_FIELD_ELIDE.get(fname)
            if not rule:
                continue
            c_kind = PP_ELIDE_C_ENUM[rule]
            lines.append(f'    {{"{fname}", {c_kind}}},')
        lines.extend([
            "};",
            "static const size_t ASR_PP_VARIABLE_ELIDE_COUNT =",
            "    sizeof(ASR_PP_VARIABLE_ELIDE) / sizeof(ASR_PP_VARIABLE_ELIDE[0]);",
            "",
        ])
    else:
        lines.extend([
            "static const ASR_PpVariableElideRule ASR_PP_VARIABLE_ELIDE[] = {};",
            "static const size_t ASR_PP_VARIABLE_ELIDE_COUNT = 0;",
            "",
        ])

    enum_fields = collect_variable_enum_pp_fields(variable)
    lines.extend([
        "typedef const char *(*ASR_PpEnumNameFn)(int64_t);",
        "",
        "typedef struct {",
        "    const char *field;",
        "    const char *attr_category;",
        "    ASR_PpEnumNameFn name_fn;",
        "} ASR_PpEnumFieldDesc;",
        "",
        "static const ASR_PpEnumFieldDesc ASR_PP_ENUM_FIELDS[] = {",
    ])
    for fname, asdl_type in enum_fields:
        fn = f"asr_enum_{snake_case(asdl_type)}_name"
        cat = enum_pp_attr_category(asdl_type)
        lines.append(f'    {{"{fname}", "{cat}", {fn}}},')
    lines.extend([
        "};",
        "static const size_t ASR_PP_ENUM_FIELDS_COUNT =",
        "    sizeof(ASR_PP_ENUM_FIELDS) / sizeof(ASR_PP_ENUM_FIELDS[0]);",
        "",
        "static inline const ASR_PpEnumFieldDesc *asr_pp_lookup_enum_field(",
        "        const char *field) {",
        "    if (!field) {",
        "        return NULL;",
        "    }",
        "    for (size_t i = 0; i < ASR_PP_ENUM_FIELDS_COUNT; ++i) {",
        "        if (strcmp(field, ASR_PP_ENUM_FIELDS[i].field) == 0) {",
        "            return &ASR_PP_ENUM_FIELDS[i];",
        "        }",
        "    }",
        "    return NULL;",
        "}",
        "",
        "static inline bool asr_pp_apply_elide_rule(",
        "        ASR_PpElideKind kind, MLIR_OpHandle op, const char *field) {",
        "    switch (kind) {",
        "    case ASR_PP_ELIDE_ALWAYS:",
        "        return true;",
        "    case ASR_PP_ELIDE_I64_ZERO:",
        "        return asr_get_field_i64(op, field, 0) == 0;",
        "    case ASR_PP_ELIDE_BOOL_FALSE:",
        "        return !asr_get_field_bool(op, field, false);",
        "    case ASR_PP_ELIDE_STR_EMPTY:",
        "        return asr_get_field_str(op, field).size == 0;",
        "    default:",
        "        return false;",
        "    }",
        "}",
        "",
        "static inline bool asr_pp_variable_field_is_default(",
        "        const char *field, MLIR_OpHandle op) {",
        "    for (size_t i = 0; i < ASR_PP_VARIABLE_ELIDE_COUNT; ++i) {",
        "        if (strcmp(field, ASR_PP_VARIABLE_ELIDE[i].field) == 0) {",
        "            return asr_pp_apply_elide_rule(",
        "                ASR_PP_VARIABLE_ELIDE[i].kind, op, field);",
        "        }",
        "    }",
        "    return false;",
        "}",
        "",
        "static inline const char *asr_pp_enum_field_name(",
        "        const char *field, int64_t v) {",
        "    const ASR_PpEnumFieldDesc *desc = asr_pp_lookup_enum_field(field);",
        "    if (!desc || !desc->name_fn) {",
        "        return NULL;",
        "    }",
        "    return desc->name_fn(v);",
        "}",
        "",
        "static inline const char *asr_pp_enum_attr_category(const char *field) {",
        "    const ASR_PpEnumFieldDesc *desc = asr_pp_lookup_enum_field(field);",
        "    if (desc && desc->attr_category) {",
        "        return desc->attr_category;",
        "    }",
        "    return field;",
        "}",
        "",
    ])
    return "\n".join(lines)


def write_outputs(
    ops: list[dict],
    enums: dict[str, list[str]],
    out_mlir_dir: Path,
    out_codegen_dir: Path,
) -> None:
    out_mlir_dir.mkdir(parents=True, exist_ok=True)

    outputs = {
        out_mlir_dir / "asr_dialect_schema.h": gen_schema_h(ops),
        out_mlir_dir / "asr_dialect_api_generated.h": gen_api_generated_h(ops),
        out_mlir_dir / "asr_dialect_lowering_dispatch.h": gen_lowering_dispatch_h(ops),
        out_mlir_dir / "asr_dialect_enum_print.h": gen_enum_print_h(enums),
        out_mlir_dir / "asr_dialect_print_policy.h": gen_print_policy_h(ops),
    }
    for path, content in outputs.items():
        path.write_text(content, encoding="utf-8")
        print(f"Wrote {path} ({len(content)} bytes)")
    update_visitor_sources(out_codegen_dir, ops)


def check_outputs(
    ops: list[dict],
    enums: dict[str, list[str]],
    out_mlir_dir: Path,
    out_codegen_dir: Path,
) -> bool:
    expected = {
        out_mlir_dir / "asr_dialect_schema.h": gen_schema_h(ops),
        out_mlir_dir / "asr_dialect_api_generated.h": gen_api_generated_h(ops),
        out_mlir_dir / "asr_dialect_lowering_dispatch.h": gen_lowering_dispatch_h(ops),
        out_mlir_dir / "asr_dialect_enum_print.h": gen_enum_print_h(enums),
        out_mlir_dir / "asr_dialect_print_policy.h": gen_print_policy_h(ops),
    }
    ok = True
    for path, content in expected.items():
        if not path.exists():
            print(f"MISSING: {path}", file=sys.stderr)
            ok = False
            continue
        existing = path.read_text(encoding="utf-8")
        if existing != content:
            print(f"STALE: {path}", file=sys.stderr)
            ok = False
    ok = check_visitor_sources(out_codegen_dir, ops) and ok
    return ok


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--asdl", type=Path, required=True)
    parser.add_argument("--out-mlir-dir", type=Path, required=True)
    parser.add_argument("--out-codegen-dir", type=Path, required=True,
                        help="libasr/codegen directory for visitor .h/.cpp")
    parser.add_argument("--check", action="store_true",
                        help="Verify committed generated files match ASR.asdl")
    args = parser.parse_args()

    mod = asdl.parse(str(args.asdl))
    ops = collect_ops(mod)
    enums = collect_simple_enums(mod)
    print(f"Generated {len(ops)} dialect ops")

    if args.check:
        return 0 if check_outputs(ops, enums, args.out_mlir_dir,
                                   args.out_codegen_dir) else 1

    write_outputs(ops, enums, args.out_mlir_dir, args.out_codegen_dir)
    return 0


if __name__ == "__main__":
    sys.exit(main())
